### ISSUE TITLE
wordpress doesn't start - manual install

### ISSUE THREAD

**Issue by tausciam** [bitnami/bitnami-docker-wordpress-nginx#13]
I just installed your docker image from hub.docker.com and followed the steps for manual installation as I do not have docker compose. I'm running current Arch Linux and installed docker. I also installed your Mariadb container using the manual steps in this installation:

```console
$ docker run -d --name mariadb -e ALLOW_EMPTY_PASSWORD=yes -e MARIADB_USER=bn_wordpress -e MARIADB_DATABASE=bitnami_wordpress --net wordpress-tier --volume mariadb_data:/home/webuser/bitnami bitnami/mariadb:latest
```

First, I saw in the scripts a bitnami directory was needed for persistance. I'm running a non-root install of docker so I put it in my user directory.  I then ran the command:

```
$ docker run -d --name wordpress -p 80:80 -p 443:443 -e ALLOW_EMPTY_PASSWORD=yes -e WORDPRESS_DATABASE_USER=bn_wordpress -e WORDPRESS_DATABASE_NAME=bitnami_wordpress --net wordpress-tier --volume wordpress_data:/home/webuser/bitnami --volume /home/webuser/wordpress-vhosts.conf:/home/webuser/bitnami/nginx/conf/server_blocks/wordpress-vhosts.conf bitnami/wordpress-nginx:latest
```

The /home/webuser/bitnami directory stays empty. The containers start up fine. However, when I go to the website, I see nginx. Wordpress doesn't start. 

Docker version:

```
Client: Docker Engine - Community
 Version:           master-dockerproject-2019-12-11
 API version:       1.41
 Go version:        go1.12.12
 Git commit:        08eaead2
 Built:             Wed Dec 11 23:52:32 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          master-dockerproject-2019-12-11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       1347481
  Built:            Wed Dec 11 23:58:15 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: master-dockerproject-2019-12-11
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc version: d736ef14f0288d6993a1845745d6756cfc9ddd5a
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.4.13-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.637GiB
 Name: beelink
 ID: BNB7:PO3Y:6XND:7BMS:SU4F:MVAT:V3NM:5OHN:NK6P:V6L6:4KUF:W7U4
 Docker Root Dir: /home/webuser/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

I saw in another bug report you had them download a server block conf. I did that and made all the subdirectories, put it in the right place on my host. I then stopped and restarted the container. Still...nginx shows up, but wordpress doesn't.

**Comment by juan131** [comment]
Hi @tausciam 

You're using the command below to install WordPress:

```console
$ docker run -d --name wordpress \
    -p 80:80 -p 443:443 \
    -e ALLOW_EMPTY_PASSWORD=yes \
    -e WORDPRESS_DATABASE_USER=bn_wordpress \
    -e WORDPRESS_DATABASE_NAME=bitnami_wordpress \
    --net wordpress-tier \
    --volume wordpress_data:/home/webuser/bitnami \
    --volume /home/webuser/wordpress-vhosts.conf:/home/webuser/bitnami/nginx/conf/server_blocks/wordpress-vhosts.conf bitnami/wordpress-nginx:latest
```

The line below means "mount the volume `wordpress_data` at the container's mountpath `/home/webuser/bitnami`". However, the WordPress data is persisted at `/bitnami/wordpress`.

```console
    --volume wordpress_data:/home/webuser/bitnami \
```

Therefore, you have two options to persist WordPress data:

- Use a "docker volume"

```console
    --volume wordpress_data:/bitnami/wordpress \
```

- Mount a local directory from your host:

```console
    --volume /your-local-directory:/bitnami/wordpress \
```

Sth similar is happening when you're trying to mount your custom serverblock.

Could you please also share the logs of the container? Just paste the output of running the command below:

```console
$ docker logs wordpress
```

**Comment by tausciam** [comment]
Ok, I stopped and removed wordpress. I restarted a new container with the following:

docker run -d --name wordpress -p 80:80 -p 443:443 -e ALLOW_EMPTY_PASSWORD=yes -e WORDPRESS_DATABASE_USER=bn_wordpress -e WORDPRESS_DATABASE_NAME=bitnami_wordpress --net wordpress-tier --volume wordpress_data:/bitnami --volume /home/webuser/wordpress-vhosts.conf:/bitnami/nginx/conf/server_blocks/wordpress-vhosts.conf --volume /home/webuser/wordpress:/bitnami/wordpress bitnami/wordpress-nginx:latest

I now have a populated /home/webuser/wordpress directory

here's docker logs wordpress:

Welcome to the Bitnami wordpress-nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues
Send us your feedback at containers@bitnami.com

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing nginx
nami    INFO  nginx successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  ==> Preparing PHP environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
wordpre INFO 
wordpre INFO  ########################################################################
wordpre INFO   Installation parameters for wordpress:
wordpre INFO     First Name: FirstName
wordpre INFO     Last Name: LastName
wordpre INFO     Username: user
wordpre INFO     Password: **********
wordpre INFO     Email: user@example.com
wordpre INFO     Blog Name: User's Blog!
wordpre INFO     Table Prefix: wp_
wordpre INFO   (Passwords are not shown for security reasons)
wordpre INFO  ########################################################################
wordpre INFO 
nami    INFO  wordpress successfully initialized
INFO  ==> Starting wordpress... 
INFO  ==> Starting PHP-FPM...
INFO  ==> Starting NGINX...
172.18.0.1 - - [24/Jan/2020:13:27:25 +0000] "POST / HTTP/1.1" 405 157 "-" "Red"

**Comment by juan131** [comment]
Hi @tausciam 

It looks like WordPress was successfully initialised! 

Are you able to access it through localhost (since you're mapping the ports `80:80`)?  In case you're not, could you share the content of the custom serverblock you mounted (the one you have at `/home/webuser/wordpress-vhosts.conf`)?

**Comment by tausciam** [comment]
Sorry...I went ahead and went with a plain nginx container
