### ISSUE TITLE
 wordpress-nginx won’t start if you add a docker-entrypoint-init.d script

### ISSUE THREAD

**Issue by eriknolte** [bitnami/bitnami-docker-wordpress-nginx#15]
**Description**

When I add a docker-entrypoint-init.d script to the wordpress-nginx container, the container fails to start because it can't touch /bitnami/wordpress-nginx/.user_scripts_initialized.

The image has wordpress installed in /bitnami/wordpress but set BITNAMI_APP_NAME to wordpress-nginx so touching /bitnami/$BITNAMI_APP_NAME/.user_scripts_initialized in post-init.sh fails because there is no /bitnami/wordpress-nginx directory.

Either Wordpress should be installed in /bitnami/wordpress-nginx, BITNAMI_APP_NAME should be set to just wordpress, or post-init.sh should use something other than $BITNAMI_APP_NAME.

I'm using myscript to run update-ca-certificates on first boot so that LDAP START_TLS works with my LDAP server's cert that I map to /usr/local/share/ca-certificates/my-ldap-cert.crt.

**Steps to reproduce the issue:**

1. Create the `myscript` on the host
```
#!/bin/bash
update-ca-certificates
```
2. chmod +x myscript
3. map the script to the container with a volume mapping
```
- <dir>/myscript:/docker-entrypoint-init.d/myscript:ro
```
4. start container with docker-compose

**Describe the results you received:**

myscript runs, but `touch /bitnami/$BITNAMI_APP_NAME/.user_scripts_initialized` exits 1 with the message `touch: cannot touch '/bitnami/wordpress-nginx/.user_scripts_initialized: no such file or directory` and the container start fails.

**Describe the results you expected:**

Container should start, myscript should run, /bitnami/wordpress{-nginx}/.user_scripts_initialized should be created, and the container should keep running.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens continuously until you add `mkdir -p /bitnami/wordpress-nginx` to myscript.

**Version**

- Output of `docker version`:

```
17.09.1-ce, build 0bbe3ac
```

- Output of `docker info`:

```
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay qnet
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c000fd07a23e5904618abdbb31f75c44865ef13 (expected: 06b9cb35161009dcb7123345749fef02f7cea8e0)
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.24-qnap
Operating System: QTS 4.4.1 (20191206)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.66GiB
Name: ironboundbay.myqnapcloud.com
ID: C2N2:YIUX:LMAH:YVO5:OVIB:SQXV:5NT4:ISHP:6ECX:QAED:LNJ3:WJOR
Docker Root Dir: /share/CE_CACHEDEV1_DATA/Container/container-station-data/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 116
 Goroutines: 121
 System Time: 2020-01-31T15:35:08.511070018-07:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.5.1
CPython version: 2.7.3
OpenSSL version: OpenSSL 1.0.2l  25 May 2017
```

host uname `4.14.24-qnap #1 SMP Fri Dec 6 11:32:43 CST 2019 x86_64 GNU/Linux`

**Comment by andresbono** [comment]
Hi @eriknolte, thanks for reporting the issue. We could reproduce the issue.

We will release a new version of the container fixing it, but in the meantime, can you specify the environment variable `BITNAMI_APP_NAME=wordpress` when you run the container?

Thanks again for filling the issue.

**Comment by eriknolte** [comment]
I've taken a different approach and run the command manually since other bitnami images like dokuwiki don't (currently?) support docker-entrypoint-init.d.

**Comment by andresbono** [comment]
Thanks for letting us know @eriknolte. In any case, we will keep this issue open until we resolve the issue.

**Comment by andresbono** [comment]
Hi @eriknolte, we have now released new versions of https://github.com/bitnami/bitnami-docker-dokuwiki/commit/804294a1298a09d815799d4736c3057f53212f66 and `wordpress-nginx` https://github.com/bitnami/bitnami-docker-wordpress-nginx/commit/4d72a461b384ad7d563695e84530260ad17f17d8 that fix this issue, in case you want to go back to the standard approach.
