### ISSUE TITLE
Can I use this image with wordpress helm chart?

### ISSUE THREAD

**Issue by fr0der1c** [bitnami/bitnami-docker-wordpress-nginx#17]
**Description**

I'm using [this](https://github.com/helm/charts/tree/master/stable/wordpress) helm chart to deploy WordPress to my cluster. The default image `bitnami/wordpress` is using Apache, but I prefer Nginx. So I wonder if it's possible to use this image to work with the helm chart.

**Comment by andresbono** [comment]
Hi @fr0der1c, you should be able to run it, but we can't guarantee the correct behavior as we don't test this scenario.

You will need to mount a server-block as a config map or a similar approach in the WordPress container. You can see what is being done in the docker-compose of this repository:

https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/730c2fe24558ecd1412e1ec8de497780af917dec/docker-compose.yml#L18

After doing that modification in the chart, you should be able to run it:

```
helm install --name wordpress . --set image.repository=bitnami/wordpress-nginx --set image.tag=5.3.2-debian-10-r8
```

Keep in mind that you won't be able to use some of the features of the chart such as the metrics exporter for Apache.

**Comment by TheAggressive** [comment]
Hello, I'm running into an issue trying to do the steps above as I would rather run WordPress with NGINX over Apache in helm. (side question, why apache by default and not option to use either?)

What I did is in my chart values, I changed the repository and tag to the follows
```
values.yaml
---

wordpress:
  image:
    registry: docker.io
    repository: bitnami/wordpress-nginx
    tag: "5.6.0"
```

I then made a config map to mount into the `/opt/bitnami/nginx/conf/server_blocks` with the above `wordpress-server-block.conf` contents. 

```
server-block-configmap.yaml
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: wordpress-server-block
data:
  wordpress-server-block.conf: |-
    server {
      listen 0.0.0.0:80;
      server_name _;

      root /opt/bitnami/wordpress;
      index index.php;

      location / {
        try_files $uri $uri/ /index.php?q=$uri&$args;
      }

      if (!-e $request_filename)
      {
        rewrite ^/(.+)$ /index.php?q=$1 last;
      }

      location ~ \.php$ {
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }
    }
```

I then added `extraVolumes` and `extraVolumeMounts` to values.yaml

```
values.yaml
---

wordpress:
  extraVolumes:
    - name: wordpress-server-block-config
      configMap:
        name: wordpress-server-block

  extraVolumeMounts:
    - name: wordpress-server-block-config
      mountPath: /opt/bitnami/nginx/conf/server_blocks
      readOnly: true
```

When I `helm install`... the WordPress Pod status ends up `CrashLoopBackOff`

I then looked at the logs and this is what I see:
```
> kubectl logs wordpress-795c489b6-z9fd6

Welcome to the Bitnami wordpress-nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing nginx
Error executing 'postInstallation': Files to substitute resolved to an empty list
```

Any idea to get this working? I would really love to use your WordPress with NGINX image over the Apache version for optimal performance.

Thank you for all you do!

**Comment by mysticaltech** [comment]
It would be great to official add a helm chart for wordpress-nginx, it is by far a superior solution to using Apache!

**Comment by miguelaeh** [comment]
Hi @mysticaltech ,
The chart itself would be almost a copy of the current one. As andres mentioned above, you should be able to run the chart with a different image, and it provides all kinds of customization inputs such as extra volumes, extra configmaps, commands, args, etc.
Please give a try and let us know if you find any issue

**Comment by mysticaltech** [comment]
Thanks for the info @miguelaeh, ideally I would have loved to use it through Kubeapps, so if I start customizing stuff, I will lose a lot of the hands-off experience (especially for upgrades). So for now I will use the standard version with Apache, but then again I really believe that WordPress powered by Nginx or another server like Caddy is by far a superior solution to using Apache, especially when it comes to speed and load handling for high traffic sites. And now that CoreWebVitals have become essential for SEO, this becomes even more important.

If you folks could create an official chart for this container it would be awesome, and I am 100% sure that it will be extremely well received by the community. Any serious sys admin will not go and voluntarily use Apache as a server in 2021.

**Comment by mysticaltech** [comment]
Anyway, I will give it a shot and let you folks know. Just a quick question, I have seen a reference to htaccess somewhere in the container definition. That container uses Nginx with php-fpm correct, Apache is not involved?

**Comment by miguelaeh** [comment]
Thank you very much for the feedback. We will discuss your suggestions and evaluate if we should create a new chart or give out of the box support to this one.

**Comment by mysticaltech** [comment]
Just to confirm folks, via Kubeapps I selected WordPress CMS chart, then changed to:

```
image:
  registry: docker.io
  repository: bitnami/wordpress-nginx
  tag: 5.7.2
```

Also disabled the metrics pod with:

```
metrics:
  ## @param metrics.enabled Start a sidecar Prometheus exporter to expose metrics
  ##
  enabled: false
```

It works fine without adding a ConfigMap. Now, is the default Nginx conf, server blocks, etc, optimized for WordPress or not? Like only passing .php files to php-fpm and not images, .js, and .css files (returning those directly)?

**Comment by mysticaltech** [comment]
Indeed Nginx config is optimized enough, so all good, just as a share of info for others:

1001@test-wp-wordpress-f56964fc4-wggwd:/$ cat /opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf
```
server {
    # Port to listen on, can also be set in IP:PORT format
    listen 8080 default_server;
    root /opt/bitnami/wordpress;
    # Catch-all server block
    # See: https://nginx.org/en/docs/http/server_names.html#miscellaneous_names
    server_name _;
    # BEGIN Fix for WordPress plugins and themes
    # Certain WordPress plugins and themes do not properly link to PHP files because of symbolic links
    # https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/43
    rewrite ^/bitnami/wordpress(/.*) $1 last;
    # END Fix for WordPress plugins and themes
    # BEGIN WordPress
    # https://wordpress.org/support/article/nginx/#general-wordpress-rules
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }
    # END WordPress
    include  "/opt/bitnami/nginx/conf/bitnami/*.conf";
}
```

1001@test-wp-wordpress-f56964fc4-wggwd:/$ cat /opt/bitnami/nginx/conf/bitnami/                                 
`certs/                     php-fpm.conf               protect-hidden-files.conf ` 

1001@test-wp-wordpress-f56964fc4-wggwd:/$ cat /opt/bitnami/nginx/conf/bitnami/php-fpm.conf 
```
index index.html index.htm index.php;
location ~ \.php$ {
    fastcgi_read_timeout 300;
    fastcgi_pass   unix:/opt/bitnami/php/var/run/www.sock;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME $request_filename;
    include        fastcgi_params;
}
1001@test-wp-wordpress-f56964fc4-wggwd:/$ cat /opt/bitnami/nginx/conf/bitnami/protect-hidden-files.conf 
# Deny all attempts to access hidden files such as .htaccess or .htpasswd
location ~ /\. {
    deny all;
}
```

**Comment by miguelaeh** [comment]
Hi @mysticaltech ,
What you see inside the pods are the configuration generated by the container here https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/87f11fe0a82696a69f4f5e8f08847e391a874de2/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L597

**Comment by mysticaltech** [comment]
Oh wow, interesting @miguelaeh, it shows the config options possible. Thanks 🙏
