### ISSUE TITLE
docker-compose.yml volumes - mariadb cannot create directory

### ISSUE THREAD

**Issue by geeksupport1** [bitnami/bitnami-docker-wordpress-nginx#20]
**Description**
```
Error
mariadb_1: mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
```

1. On a fresh install, wordpress works, but no volume is found in the host file system.

Using windows 10 WSL.

docker daemon running on wsl.

2. the purpose is to adjust volumes so that the maria_db and wordpress_data is mapped to host filesystem

**Steps to reproduce the issue:**

Following the documentation at
https://github.com/bitnami/bitnami-docker-wordpress-nginx#mount-host-directories-as-data-volumes-with-docker-compose

```diff
 ...
 services:
   mariadb:
     ...
     volumes:
-      - 'mariadb_data:/bitnami/mariadb'
+      - /path/to/mariadb-persistence:/bitnami/mariadb
   ...
   wordpress:
      ...
     volumes:
-      - 'wordpress_data:/bitnami/wordpress
+      - /path/to/wordpress-persistence:/bitnami/wordpress
       - ./wordpress-vhosts.conf:/bitnami/nginx/conf/server_blocks/wordpress-vhosts.conf
   ...
-volumes:
-  mariadb_data:
-    driver: local
-  wordpress_data:
-    driver: local
```
**Describe the results you received:**
```
Error
mariadb_1: mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
```
The mysql service dies and everything else then dies.

**Describe the results you expected:**

MariaDb and wordpress is expected to be running.

**Version**

- Output of `docker version`:

```
 docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker-compose version` (if applicable):
```
docker-compose version docker-compose version 1.17.1, build unknown docker-py version: 2.5.1 CPython version: 2.7.15+ OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Comment by carrodher** [comment]
What are the permissions in your local machine assigned to the persistence paths?
You need to ensure that the local folders have the proper permissions because the container needs to write in that directories.

**Comment by geeksupport1** [comment]
Hi carrodher,

Thanks for responding.

Here is the docker-compose.yml
`
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress-nginx:5'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./wordpress_data:/bitnami/wordpress
      - './wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf:ro'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
`

I am trying to get volumes to mount to a local directory.

I have read

https://github.com/bitnami/bitnami-docker-mariadb/issues/193
https://github.com/bitnami/bitnami-docker-suitecrm/issues/72
https://github.com/bitnami/bitnami-docker-mariadb/issues/186
https://techoverflow.net/2018/12/15/solving-bitnami-docker-redmine-cannot-create-directory-bitnami-mariadb-permission-denied/

====================================
For 
https://github.com/bitnami/bitnami-docker-mariadb/issues/193

In the fix addressed in here
method 1
https://github.com/bitnami/bitnami-docker-mariadb/issues/193

mkdir mariadb_data && sudo chmod o+w mariadb_data

sudo chmod o+w mariadb-data.

after these cmd, I ran 
docker-compose up --force-create

I get

`
mariadb_1    | mariadb 20:18:56.76 INFO  ==> Initializing mariadb database
mariadb_1    | mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
bitwpng_mariadb_1 exited with code 1
`

Since the container exited, I do not know the permissions.
However, in I used named volumes and entered the maria_db container, it was [I have noname] or something like that.
=====================================
method 2

The script runs without problem, but the host directory is empty.

=====================================
https://github.com/bitnami/bitnami-docker-wordpress-nginx

=====================================

I read 
https://github.com/bitnami/bitnami-docker-suitecrm/issues/72

it's about 
'
services:
  fix-mariadb-permissions:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
'

but they also refer to full paths.

=================

It's confusing why an official release from bitnami cannot mount volumes properly..

Thanks.

**Comment by carrodher** [comment]
Can you execute the following command (and paste here the output) **in the same folder where your `docker-compose.yaml` is located**?
```
$ ls -alFh
```

As you are using local volumes and path, you need to ensure that the `mariadb_data`, `wordpress_data` and your `wordpress-server-block.conf` are located in the same directory with the `docker-compose.yaml`, something like that:
```
$ ls -alFh
total 20K
drwxrwxr-x  4 bitnami bitnami 4.0K Mar 31 07:25 ./
drwxrwxr-x 70 bitnami bitnami 4.0K Mar 31 07:25 ../
-rw-rw-r--  1 bitnami bitnami  753 Mar 31 07:15 docker-compose.yml
drwxrwxrwx  3 bitnami bitnami 4.0K Mar 31 07:24 mariadb_data/
drwxrwxrwx  3 bitnami bitnami 4.0K Mar 31 07:24 wordpress_data/
```
Please, note that in my case I didn't create the `wordpress-server-block.conf`.

Apart from that, you need to ensure that those folders have the proper permissions, in this case, it's enough providing writable permission for `others`.

If you don't have the folders you can create it and give the permissions by running.
```
mkdir wordpress_data mariadb_data
sudo chmod o+x wordpress_data mariadb_data
```
please, note that you can avoid the `mkdir` command if the folders already exist.

In the same way, you also need to put your `wordpress-server-block.conf` in that place.

In the end, we should think that we are mounting host directories as data volumes, so those host directories should exist in your local machine having the proper permissions.

**Comment by geeksupport1** [comment]
Hi carrodher,

Thanks for responding.

`
 !ls
ls -alFh
total 53K
drwxr-xr-x 1 geek geek    512 Mar 31 21:48 ./
drwxrwxrwx 1 geek geek    512 Mar 29 21:41 ../
-rw-r--r-- 1 geek geek    12K Mar 31 21:49 .docker-compose.yml.swp
drwxr-xr-x 1 geek geek    512 Mar 30 18:41 .git/
drwxr-xr-x 1 geek geek    512 Mar 29 14:36 .github/
drwxr-xr-x 1 geek geek    512 Mar 29 14:36 5/
-rw-r--r-- 1 geek geek    557 Mar 29 14:36 LICENSE
-rw-r--r-- 1 geek geek    23K Mar 29 14:36 README.md
-rw-r--r-- 1 geek geek    753 Mar 31 06:10 docker-compose.yml
-rw-r--r-- 1 geek docker  832 Mar 30 19:26 docker-compose.yml.orig
drwxr-xrwx 1 root root    512 Mar 31 06:01 mariadb_data/
-rw-r--r-- 1 geek geek   2.7K Mar 29 14:36 test.yaml
-rw-r--r-- 1 geek geek    454 Mar 31 06:07 wordpress-server-block.conf
drwxr-xrwx 1 root root    512 Mar 31 06:01 wordpress_data/
`
 ==================

I reran the docker-compose file.

`
 docker-compose up --force-recreateRecreating bitwpng_mariadb_1 ...
Recreating bitwpng_mariadb_1 ... done
Recreating bitwpng_wordpress_1 ...
Recreating bitwpng_wordpress_1 ... done
Attaching to bitwpng_mariadb_1, bitwpng_wordpress_1
mariadb_1    | mariadb 11:50:50.60
mariadb_1    | mariadb 11:50:50.61 Welcome to the Bitnami mariadb container      mariadb_1    | mariadb 11:50:50.61 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1    | mariadb 11:50:50.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1    | mariadb 11:50:50.62 Send us your feedback at containers@bitnami.com
mariadb_1    | mariadb 11:50:50.62
mariadb_1    | mariadb 11:50:50.62 INFO  ==> ** Starting MariaDB setup **        wordpress_1  |
mariadb_1    | mariadb 11:50:50.68 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
wordpress_1  | Welcome to the Bitnami wordpress-nginx container
wordpress_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx
wordpress_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues
mariadb_1    | mariadb 11:50:50.68 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress_1  | Send us your feedback at containers@bitnami.com
mariadb_1    | mariadb 11:50:50.70 INFO  ==> Initializing mariadb database       wordpress_1  |
wordpress_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1    | mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
bitwpng_mariadb_1 exited with code 1
wordpress_1  | nami    INFO  Initializing php
wordpress_1  | nami    INFO  php successfully initialized
wordpress_1  | nami    INFO  Initializing nginx
wordpress_1  | nami    INFO  nginx successfully initialized
wordpress_1  | nami    INFO  Initializing mysql-client
wordpress_1  | nami    INFO  mysql-client successfully initialized
wordpress_1  | nami    INFO  Initializing wordpress
wordpress_1  | wordpre INFO  ==> Preparing Varnish environment
wordpress_1  | wordpre INFO  ==> Preparing Apache environment
wordpress_1  | wordpre INFO  ==> Preparing PHP environment
wordpress_1  | mysql-c INFO  Trying to connect to MySQL server
wordpress_1  | Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
bitwpng_wordpress_1 exited with code 1
`
Did n't work.

========================

I finally did this and it worked

`
 sudo chmod 777 wordpress_data/ mariadb_data/
`

so

`

ls -alFh
total 37K
drwxr-xr-x 1 geek geek    512 Mar 31 22:10 ./
drwxrwxrwx 1 geek geek    512 Mar 29 21:41 ../
drwxr-xr-x 1 geek geek    512 Mar 30 18:41 .git/
drwxr-xr-x 1 geek geek    512 Mar 29 14:36 .github/
drwxr-xr-x 1 geek geek    512 Mar 29 14:36 5/
-rw-r--r-- 1 geek geek    557 Mar 29 14:36 LICENSE
-rw-r--r-- 1 geek geek    23K Mar 29 14:36 README.md
-rw-r--r-- 1 geek geek    972 Mar 31 22:10 docker-compose.yml
-rw-r--r-- 1 geek docker  832 Mar 30 19:26 docker-compose.yml.orig
drwxrwxrwx 1 root root    512 Mar 31 22:08 mariadb_data/
-rw-r--r-- 1 geek geek   2.7K Mar 29 14:36 test.yaml
-rw-r--r-- 1 geek geek    454 Mar 31 06:07 wordpress-server-block.conf
drwxrwxrwx 1 root root    512 Mar 31 06:01 wordpress_data/
`
============================

so I have 

`
ls -alFh mariadb_data/
total 0
drwxrwxrwx 1 root root 512 Mar 31 22:13 ./
drwxr-xr-x 1 geek geek 512 Mar 31 22:13 ../
drwxr-xr-x 1 1001 1001 512 Mar 31 22:08 _data/
drwxr-xr-x 1 1001 root 512 Mar 31 22:13 data/
geek@TERESA-E595:/e/PROJECTS/DOCKER/bit-wp-ng$
geek@TERESA-E595:/e/PROJECTS/DOCKER/bit-wp-ng$ ls -alFh wordpress_data/
total 0
drwxrwxrwx 1 root root 512 Mar 31 22:13 ./
drwxr-xr-x 1 geek geek 512 Mar 31 22:13 ../
drwxr-xr-x 1 1001 root 512 Mar 31 22:13 wp-content/
`
=================================

At the moment, I am using it locally, but ..,

How would I deploy this in production, given the permissions issues?

It's likely I would be using Azure.

Thanks doe your help carrodher.

**Comment by carrodher** [comment]
Hi, you don't need to set `777` as the permissions, there are a ton of possibilities to have it working, I mean, different user/group/permission combinations.

Containers are executed as a non-root user (user `1001` that belongs to the `root` group), so you need to ensure that your local folder is writable by this user, the `root` group or even by others.

If you **manually create the folders**, the permissions should be something like:
```
drwxrwxr-x  2 geek geek 4.0K Apr  1 16:50 mariadb_data/
drwxrwxr-x  2 geek geek 4.0K Apr  1 16:50 wordpress_data/
```
where the `geek` user/group has all the permissions but this user/group is not the one running the container, so it will not work. In that case, you need to provide permission for others with `sudo chmod o+w mariadb_data wordpress_data wordpress-server-block.conf` but that is a `777`.

If **docker created the folders**, those folders look like:
```
drwxr-xr-x  2 root    root    4.0K Apr  1 16:53 mariadb_data/
drwxr-xr-x  2 root    root    4.0K Apr  1 16:53 wordpress_data/
```
note that now the folders belong to the `root` user/group. As I mentioned, the user `1001` belongs to the root group, so in that case, you need to provide permission for the group with `sudo chmod g+x mariadb_data wordpress_data wordpress-server-block.conf`.

Another option is to change the user of the folders with `sudo chown 1001 wordpress_data/ mariadb_data wordpress-server-block.conf`.

In the end, you need to ensure the user `1001` (that belongs to the `root` group) has writable permission over those folders, and you can do it in several ways without using `777`.

Please, let me know if it is not clear and I will try to explain in a different way.

Here you can find some resource related to non-root containers:
- https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/
- https://engineering.bitnami.com/articles/running-non-root-containers-on-openshift.html
- https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html

**Comment by geeksupport1** [comment]
Hi carrodher,

Thanks for the explanation. I feel your explanation should be on the front page for others to be mindful of. Or maybe in the bitnami-MariaDb docker page. 

 So I create the  directories
>mariadb-data
>wordpress-data

====
>docker-compose up --force-recreate 

====

>  ls -al
> total 37
> drwxr-xr-x 1 geek geek     512 Apr  2 21:54 .
> drwxrwxrwx 1 geek geek     512 Mar 29 21:41 ..
> drwxr-xr-x 1 geek geek     512 Mar 30 18:41 .git
> drwxr-xr-x 1 geek geek     512 Mar 29 14:36 .github
> drwxr-xr-x 1 geek geek     512 Mar 29 14:36 5
> -rw-r--r-- 1 geek geek     557 Mar 29 14:36 LICENSE
> -rw-r--r-- 1 geek geek   22835 Mar 29 14:36 README.md
> -rw-r--r-- 1 geek geek     761 Apr  2 21:37 docker-compose.yml
> drwxr-xr-x 1 1001 root     512 Apr  2 21:55 mariadb-data
> drwxr-xr-x 1 1001 root     512 Apr  2 21:54 wordpress-data
> -rw-r-xr-- 1 1001 root     454 Mar 31 06:07 wordpress-server-block.conf
> 
=====
running docker-compose still hangs

=====
then
> sudo chmod g+w mariadb-data wordpress-data

=====

>  ls -al
> total 37
> drwxr-xr-x 1 geek geek     512 Apr  2 21:54 .
> drwxrwxrwx 1 geek geek     512 Mar 29 21:41 ..
> drwxr-xr-x 1 geek geek     512 Mar 30 18:41 .git
> drwxr-xr-x 1 geek geek     512 Mar 29 14:36 .github
> drwxr-xr-x 1 geek geek     512 Mar 29 14:36 5
> -rw-r--r-- 1 geek geek     557 Mar 29 14:36 LICENSE
> -rw-r--r-- 1 geek geek   22835 Mar 29 14:36 README.md
> -rw-r--r-- 1 geek geek     761 Apr  2 21:37 docker-compose.yml
> -rw-r--r-- 1 geek docker   832 Mar 30 19:26 docker-compose.yml.orig
> drwxrwxr-x 1 1001 root     512 Apr  2 21:55 mariadb-data
> -rw-r--r-- 1 geek geek    2733 Mar 29 14:36 test.yaml
> drwxrwxr-x 1 1001 root     512 Apr  2 21:54 wordpress-data
> -rw-r-xr-- 1 1001 root     454 Mar 31 06:07 wordpress-server-block.conf

=====

Then running

> docker-compose up --force-recreate 

works

===

>  cat docker-compose.yml
> version: '2'
> services:
>   mariadb:
>     image: 'bitnami/mariadb:latest'
>     volumes:
>       - ./mariadb-data:/bitnami/mariadb
>     environment:
>       - MARIADB_USER=bn_wordpress
>       - MARIADB_DATABASE=bitnami_wordpress
>       - ALLOW_EMPTY_PASSWORD=yes
>   wordpress:
>     image: 'bitnami/wordpress-nginx:latest'
>     ports:
>       - '80:8080'
>       - '443:8443'
>     volumes:
>       - ./wordpress-data:/bitnami/wordpress
>       - './wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf:ro'
>     depends_on:
>       - mariadb
>     environment:
>       - MARIADB_HOST=mariadb
>       - MARIADB_PORT_NUMBER=3306
>       - WORDPRESS_DATABASE_USER=bn_wordpress
>       - WORDPRESS_DATABASE_NAME=bitnami_wordpress
>       - ALLOW_EMPTY_PASSWORD=yes
>

**Comment by crowne** [comment]
I had the same issue trying to run docker-compose on windows.
The only way that I could get it to work was to change the user to root, by adding user: root after the image:

    image: docker.io/bitnami/mariadb:10.3
    user: root

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution). This issue will stay available to allow the community to contribute.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by crowne** [comment]
Thanks, I was wrong anyway, my problem was the syntax on the volume.
I needed to quote the string as follows, both of which work without user: root
    volumes:
      - '../../mariadb-vol:/bitnami/mariadb'
or
    volumes:
      - 'C:/dev/wp/mariadb-vol:/bitnami/mariadb'
