### ISSUE TITLE
postInstallation: EEXIST: file already exists symlink '/bitnami/wordpress/wp-content' -> '/opt/bitnami/wordpress/wp-content'

### ISSUE THREAD

**Issue by darrenbarklie** [bitnami/bitnami-docker-wordpress-nginx#21]
**Description**

Hi there.  I am trying to programmatically install custom plugins and themes on top of this Bitnami image on macOS.  Using the Dockerfile I am adding **composer.json** and **composer.lock** files from local, installing Composer in the container and runing `composer install`.

**Dockerfile**
```
FROM bitnami/wordpress-nginx

WORKDIR /bitnami/wordpress/wp-content
ADD composer.json .
ADD composer.lock .

USER 0
RUN curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
  && composer install \
  && echo "Done..."
USER 1001 
```
**composer.json**
```
{
  "name": "darrenbarklie/dockertest",
  "description": "A demo of Composer",
  "prefer-stable": true,
  "config": {
    "secure-http": false
  },
  "require": {
    "composer/installers": "^1.9",
    "fancyguy/webroot-installer": "1.0.0",
    "wpackagist-plugin/favicon-by-realfavicongenerator": "^1.3"
  },
  "repositories": {
    "packagist": {
      "type": "composer",
      "url": "http://packagist.org"
    },
    "wpackagist": {
      "type": "composer",
      "url": "http://wpackagist.org"
    }
  },
  "extra": {
    "installer-paths": {
      "plugins/{$name}": [
        "type:wordpress-plugin"
      ],
      "themes/{$name}": [
        "type:wordpress-theme"
      ],
      "mu-plugins/{$name}": [
        "type:wordpress-muplugin"
      ]
    }
  }
}
```
This works fine if I automatically inject the files, install Composer, then navigate inside the container to run `compose install`.

However scripting this appears to cause a problem, where Composer successfully installs the plugins at **/opt/bitnami/wordpress/wp-content/plugins** and runs this download/installation.  However creating content here causes the WP container postInstaller to hang, logs showing:
```
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing nginx
nami    INFO  nginx successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  ==> Preparing Varnish environment
wordpre INFO  ==> Preparing Apache environment
wordpre INFO  ==> Preparing PHP environment
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
wordpre INFO  Preparing WordPress environment
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/wordpress/wp-content' -> '/opt/bitnami/wordpress/wp-content'
```
When I try to install the plugins on the symlink location (**/bitnami/wordpress/wp-content**):
```
...
Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/wordpress/wp-content/index.php'
```
I'm using the default docker-compose file, without issue.

Any support would be appreciated.  Let me know if you require any additional logs.

**Comment by miguelaeh** [comment]
Hi @darrenbarklie ,
This is happening because the `composer install` command installs the plugins inside the `wp-content` folder, so, when the container logic tries to configure that folder it is already present because it was created by your composer install command.
To avoid this error I recommend you to use a script and execute it in the `app-entrypoint.sh` after the WordPress initialization.
You can clone the repository and here: https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/app-entrypoint.sh, just before the `exec` command, call you script.
If am not wrong that should solve the issue.

**Comment by darrenbarklie** [comment]
Thanks for the suggestion @miguelaeh -- I'll try this and report back.
