### ISSUE TITLE
ssl handshake works in debian 9 image but fails in debian 10 image

### ISSUE THREAD

**Issue by kuldeepsidhu88** [bitnami/bitnami-docker-wordpress-nginx#29]
**Description**

I was trying to run wordpress-nginx latest image which is based on Debian 10.

I am trying to integrate it with OracleCloud Email Delivery Service. When I add SMTP credentials in WP Mail SMTP plugin, it works fine in Debian 9 based image but fails with ssl handshake error in Debian 10 based image.

**Steps to reproduce the issue:**
Docker image used for Debian 10 - ```bitnami/wordpress-nginx:5```
Docker image used for Debian 9 - ```bitnami/wordpress-nginx:5-debian-9```
Try to run below command to test handshake in Debian9/10 based images. 
```
echo QUIT | openssl s_client -starttls smtp -crlf -connect smtp.email.ap-mumbai-1.oci.oraclecloud.com:587
```
**Describe the results you received:**
Debian 9 bases returns success but Debian 10 fails with below error

```
139739481552000:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1544:SSL alert number 40
```

**Describe the results you expected:**
Should have returned success in both images.

**Additional information you deem important (e.g. issue happens only occasionally):**
I was looking at wireshark ClientHello messages in both cases. I could not figure out why handshake is failing. 
WireShark captures have been uploaded at https://gofile.io/d/IdNihD
Please let me know what could be missing in Debian 10 image and how can I make handshake work successfully in it.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-37-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 5.819GiB
 Name: kuldeep-VirtualBox
 ID: QOP2:F27S:ETEW:HWXA:ZRY6:VEEN:BFQE:FHMV:M2LG:P23G:SO2X:AAHF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Virtual Box - Ubuntu 18.04 based environment.

Please let me know if any more detail is required.

**Comment by dani8art** [comment]
Hi @kuldeepsidhu88, thank you for opening the issue, I can confirm the issue. We are going to open an internal task in order to evaluate and try to figure out the root cause, unfortunately, we cannot give you an ETA, however, we would be very happy to receive your contributions, suggestion and idea in the form of PRs, if you have a chance we would be happy to handle it. Thank you again!

**Comment by beltran-rubo** [comment]
Hi @kuldeepsidhu88 

Checking this https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853730 Debian 10 disabled the 3DES algorithm or a different one because it is considered insecure. It is possible your SMTP provider is using that encryption algorithm. 

I would recommend you to change the port (587) with other one that support other SSL protocols e.g. 25, 993. I hope it helps.

**Comment by kuldeepsidhu88** [comment]
@beltran-rubo As per Oracle documentation, only ports 25 and 587 can be used. But getting ssl handshake failure in both ports.

**Comment by beltran-rubo** [comment]
I would contact your email provider to request they should support newer encryption algorithms or to switch to a different one. The container uses the default SSL configuration from Debian 10 and other distros like Ubuntu are also applying the same configuration, do not think there is anything we can do in the container itself.

**Comment by kuldeepsidhu88** [comment]
@dani8art @beltran-rubo Thanks. It seems to be an issue on the server end. I have an open SR going on with Oracle Cloud support team for this. They are investigating the issue.

I have posted this problem in StackOverflow as well https://stackoverflow.com/questions/62066630/ssl-handshake-failure-after-clienthello-in-ubuntu-20-04-and-debian-10-works-in

First answer seems to narrow down the issue to  signature algorithm support. 
Lets wait and see what Oracle says on it. I will update here.

**Comment by beltran-rubo** [comment]
Thanks for keeping us in the loop.

**Comment by kuldeepsidhu88** [comment]
Update from Oracle Support:

> The engineer investigating this behavior identified this as a potential bug and noted that fixing this may take significant time since it involves third-party open source code that is FIPS validated.
