### ISSUE TITLE
Real IP when running behind a proxy

### ISSUE THREAD

**Issue by kuldeepsidhu88** [bitnami/bitnami-docker-wordpress-nginx#30]
**Description**
I am running bitnami-wordpress-nginx container behind a [nginx-proxy ](https://github.com/nginx-proxy) container. 

It is working fine, but in logs I noticed, instead of Real IP of client/user, it is logging the nginx-proxy container's docker ip,which is not I wanted. 

I wanted wordpress container to log the real ip.

**Steps to reproduce the issue:**
As following headers are already added by nginx-proxy as mentioned here https://github.com/nginx-proxy/nginx-proxy/blob/4a99ac554824cde8be34cc173abc7cf1ef69dd7a/nginx.tmpl#L30-L31

```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
I tried to pass these as param to fascgi as below updating my **wordpress-block-conf** file
```
location ~ \.php$ {
    fastcgi_param REMOTE_ADDR $HTTP_X_REAL_IP;
    fastcgi_pass localhost:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }
```
**Describe the results you received:**
But still **REMOTE_ADDR** in wordpress container is shown as nginx-proxy docker container ip. And also in logs its showing docker ip.

**Describe the results you expected:**
But still **REMOTE_ADDR** in wordpress container should be shown as real ip. And in logs I expect to see real ip.

**Additional information you deem important (e.g. issue happens only occasionally):**
Any configuration am I missing here? How can I see the real IP of client in wordpress container logs when it is running behind nginx-proxy. 
Please let me know if any more info is required.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1009-oracle
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 976.9MiB
 Name: web-host
 ID: BXFO:UJWJ:6SLR:QHQ6:L5XN:OEE4:LLCV:FA7D:PUL3:MHBW:LO6X:XJ72
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Oracle Cloud - Ubuntu 20.04 VM Instance

**Comment by javsalgar** [comment]
Hi,

I found this information that may be useful for your case. It seems that you may also need to modify the WordPress configuration. Could you confirm that this solves the issue?

https://webapplicationconsultant.com/docker/passing-real-ip-in-wordpress-behind-proxy-or-in-docker/

**Comment by kuldeepsidhu88** [comment]
@javsalgar I have fixed it by following https://github.com/nginx-proxy/nginx-proxy/issues/130

I need to add following in the **wordpress-block-conf** file
```
 real_ip_header X-Forwarded-For;
 set_real_ip_from 0.0.0.0/0;
```
