### ISSUE TITLE
WordPress NGINX Docker Writrable file wp-config.php, create SSL, Redirect HTTP to HTTPS and configure HTTP/2 

### ISSUE THREAD

**Issue by RudyVS** [bitnami/bitnami-docker-wordpress-nginx#32]
Hi guys, I am happy to say hello, I will explain my problem: how can I configure SSL with Let's Encrypt, and secondly, I cannot write the wp file [-config.php, it should be noted that I used Bitnami stacks 2 years ago because it seems Great the fast and safe way to implement it but since I am a web developer I have been at the point of implementing a WordPress with NGINX in Docker and the installation was successful and fast without any problem until I had to try to implement an SSL certificate that with the VM stacks are easy and quick to do but in Docker I have not succeeded and neither have I been able to request the wp file [-config.php, to finish I also needed help to configure 2 more things 1. HTTP redirection to HTTPS, once the impasse and the last one would be to enable HTTP / 2 in this Docker deployment, if someone from the community could support me I would be grateful given that it is for a client who urges me to solve this problem and enter Gar the site as soon as possible, the site is currently running on GCP with Debian 10, for your help in advance thank you very much for your issue and add a comment
to the existing issue instead.

If you suspect your issue is a bug, please edit your issue description to
include the BUG REPORT INFORMATION shown below. If you fail to provide this
information within 7 days, we cannot debug your issue and we'll close it. We
will, however, reopen it if you later provide the information.
-------------------------------
    BUG REPORT INFORMATION
-------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @RudyVS ,
Regarding the SSL certificate, you can follow [this guide](https://github.com/bitnami/bitnami-docker-nginx#using-custom-ssl-certificates).

> I cannot write the wp file

Regarding this, could you be more specific?

**Comment by RudyVS** [comment]
> Hi @RudyVS ,
> Regarding the SSL certificate, you can follow [this guide](https://github.com/bitnami/bitnami-docker-nginx#using-custom-ssl-certificates).
> 
> > I cannot write the wp file
> 
> Regarding this, could you be more specific?

Thank you very much dear, I allow myself to leave my email since I do not finish understanding very well the information very kindly provided by your person, it would be of great help to me, orient me if possible, I will be grateful my email is

rudy@virtualsigma.com

**Comment by miguelaeh** [comment]
Hi @RudyVS ,
I am afraid that currently, we do not provide email support. Could you share in this thread what would you like to understand, so we can give you more information?
