### ISSUE TITLE
Feature Request > Hardcoded MARIADB_ENVNAMES

### ISSUE THREAD

**Issue by dmytropetryk** [bitnami/bitnami-docker-wordpress-nginx#33]
Is it mandatory to use MARIADB_ prefix for DB connection strings values?  If I prefer to use different DB it will be a little confused fo review code or code support.
Nice to have some universal names like:
DB_HOST=""\
DB_PORT_NUMBER="" \
DB_ROOT_PASSWORD="" \
DB_ROOT_USER="" \
in
https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/Dockerfile#L30

**Comment by joancafom** [comment]
Hi @dmytropetryk 

Thanks for your issue! This docker container was designed to work with MariaDB in mind (in fact, it is the flavour that we currently ship with it). WordPress [requires either MariaDB or MySQL](https://wordpress.org/support/article/faq-installation/#do-i-need-to-create-a-database), which at the end of the day are pretty much interchangeable.

Thanks!
