### ISSUE TITLE
How  to host multiple site with this image

### ISSUE THREAD

**Issue by AmirHosseinSaadatmand** [bitnami/bitnami-docker-wordpress-nginx#34]
HI
is there a  solution to host multiple site with this image?

thank you a lot

**Comment by carrodher** [comment]
In the case of containers with NGNIX, we don't have a solution supporting multisite out of the box, you need to configure manually the different aspects required to make it works.

We have a specific solution for WordPress Multisite to be deployed in the different Cloud provides, as an installer, or as VM: https://bitnami.com/stack/wordpress-multisite

**Comment by AmirHosseinSaadatmand** [comment]
Thank you carrodher.
and another question. where can i change port number of website in this image.
i want to use nginx as reverse proxy and bind domain to ip and poort to each site. But I don't know where I must set that.
thank you a lot.
@carlossm

**Comment by carrodher** [comment]
In [this section](https://github.com/bitnami/bitnami-docker-wordpress-nginx#customize-this-image) of the README you can find some instructions about how to customize the image, for example:

> Settings that can be adapted using environment variables. For instance, you can change the ports used by Nginx for HTTP and HTTPS, by setting the environment variables `NGINX_HTTP_PORT_NUMBER` and `NGINX_HTTPS_PORT_NUMBER` respectively.

**Comment by marcosbc** [comment]
Hi, FYI Multisite support was just added in [`5.7.1-debian-10-r22`](https://github.com/bitnami/bitnami-docker-wordpress-nginx#571-debian-10-r22). Please check [Multisite configuration](https://github.com/bitnami/bitnami-docker-wordpress-nginx#multisite-configuration) for more info.
