### ISSUE TITLE
How to add cache purge module

### ISSUE THREAD

**Issue by ambrosiora** [bitnami/bitnami-docker-wordpress-nginx#35]
**Description**

**How to add cache purge module?**

I'm trying to configure fastcgi and purge cache by following this tutorial (which is reliable, due to the official nginx website)
https://www.nginx.com/blog/9-tips-for-improving-wordpress-performance-with-nginx/#fastcgi
It also mentions that Open source version of Nginx can be compiled with the third‑party module [ngx_cache_purge](https://github.com/FRiCKLE/ngx_cache_purge)

So I assume that can be safe enough to use this module, right?

After check nginx modules, trying to find the module mentioned above, with the command `nginx -V` on container, the result was:
--prefix=/opt/bitnami/nginx
--with-http_stub_status_module
--with-http_gzip_static_module
--with-mail
--with-http_realip_module
--with-http_v2_module
--with-http_ssl_module
--with-mail_ssl_module
--with-http_gunzip_module
--with-http_auth_request_module
--with-http_sub_module
--with-http_geoip_module
--add-module=/bitnami/blacksmith-sandox/nginx-module-vts-0.1.18
--add-dynamic-module=/bitnami/blacksmith-sandox/nginx-module-geoip2-3.3.0
--add-module=/bitnami/blacksmith-sandox/nginx-module-substitutions-filter-0.20190806.0

**My issue is: Is there a way to add the module, or can you guys, with your awesome work with this image, put this module by default on next versions?**

Thank you!

**Comment by andresbono** [comment]
Hi @ambrosiora, thanks for letting us know about this module. We are going to evaluate if we can include it in NGINX Open Source component by default.

**Comment by ambrosiora** [comment]
Hi @andresbono, Thank you for reply. Currently I'm using fastcgi and works very well, so If you want more details about configuration/setup, I can share my configuration file or something like that.

Just saying, on this link I shared above, they suggest us to use this module and this plugin together:
https://wordpress.org/plugins/nginx-helper/

I also tried to install only the plugin, but nothing happens. And I guess I know why:
The directory /var/run/nginx-cache is is protected (chmod, chown) only to nginx user so, the application user (daemon) cannot do anything there, unless this module is enabled.

My workaround to clear cache is: manually SSH into container and remove all content inside nginx-cache. Not a very productive way, indeed.

Ok, thank you again, feel free to ask me anytime!

**Comment by andresbono** [comment]
@ambrosiora, just curious, are you using the container as root, right? If not, all the processes would run as `1001` by default.

And another question, where do you configure the system path to `nginx-cache`?

**Comment by ambrosiora** [comment]
Hi! @andresbono 
About using container as root, I think yes, but how can I check this?
I didn't know if the `/var/run/nginx-cache` directory already exist before I configure some adjustments on `/opt/bitnami/nginx/conf/server_blocks/https.conf` or if after do these adjustments the directory was created.
But, inside `/opt/bitnami/nginx/conf/server_blocks/https.conf` at the top line even before the `server` block I put this:

```
fastcgi_cache_path /var/run/nginx-cache levels=1:2 keys_zone=WHATAEVER_KEYZONE_NAME_HERE:100m inactive=60m;
fastcgi_cache_key "$scheme$request_method$host$request_uri";

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name foobar.com.br www.foobar.com.br;
...
```

and close to the bottom
this:

```
 ### begin fastcgi configs
  set $skip_cache 0;

  # POST requests and URLs with a query string should always go to PHP
  if ($request_method = POST) {
      set $skip_cache 1;
  }

  if ($query_string != "") {
      set $skip_cache 1;
  }

  # Don't cache URIs containing the following segments
  if ($request_uri ~* "(/wp-admin/|/inscreva-se/|/xmlrpc.php|/wp-(app|cron|login|register|mail).php|wp-.*.php|/feed/|index.php|wp-comments-popup.php|wp-links-opml.php|wp-locations.php |sitemap(_index)?.xml|[a-z0-9_-]+-sitemap([0-9]+)?.x$
    set $skip_cache 1;
  }

  # Don't use the cache for logged-in users or recent commenters
  if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_logged_in") {
    set $skip_cache 1;
  }

  #flag to make easy to check on browser if page is cached or live (HIT or MISS values)
  add_header rt-Fastcgi-Cache $upstream_cache_status;
  ### end fastcgi configs
```

and after these pre config to have more control on what page should be cached
I put some statements on this block:

```
  location ~ \.php$ {
    fastcgi_pass localhost:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;

    fastcgi_cache WHATAEVER_KEYZONE_NAME_HERE;
    fastcgi_cache_bypass $skip_cache;
    fastcgi_no_cache $skip_cache;
    fastcgi_cache_valid  60m;
  }

```
If you want I can share my entire `https.conf` file, but I don't know if is safe enough to share for everyone see, if you want mail me on my gmail: rafaelambrosio.mail

ps.: maybe I will open another issue related with `https.conf` when I try to recreate the container, with this customized `https.conf` an error raise. I only can recreate with original conf and then when container is up, change the file and reload nginx.

**Comment by andresbono** [comment]
> About using container as root, I think yes, but how can I check this?

You can exec into the container and see who is the user running the container.

Thanks for the clarifications around `/var/run/nginx-cache`.

We will update this issue when we have more news about the evaluation of the new module.

**Comment by ambrosiora** [comment]
> You can exec into the container and see who is the user running the container.

the user is root
thank you!

**Comment by ambrosiora** [comment]
Hi @andresbono

If you want to dive deep on FastCGI, I'd like to recommend this site: https://www.tecmint.com/cache-content-with-nginx/
I was facing a problem with expired FastCGI cache and I didn't know about `fastcgi_cache_revalidate` and other stuff they explain there. It was very useful indeed.

**Comment by mtogiz** [comment]
Hi @ambrosiora I also tried to set up FastCGI on this container with `non-root` user. And when i start container i got
```
2020/11/20 09:37:36 [emerg] 44#44: mkdir() "/var/run/nginx-cache" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/run/nginx-cache" failed (13: Permission denied)
```
So I saw that `ngx_cache_purge` module and `nginx-cache` folder (should be created by `root`) didn't exist before.

**Comment by andresbono** [comment]
Hi @mtogiz, the internal task to address this issue is still in our backlog. We will add the information that you are sharing there.

**Comment by mtogiz** [comment]
> Hi @mtogiz, the internal task to address this issue is still in our backlog. We will add the information that you are sharing there.

Hi @andresbono, Well noted on this. Thanks for quick reply

**Comment by marcosbc** [comment]
Hi all, FYI we documented not so long ago how to add a new module to NGINX here: https://github.com/bitnami/bitnami-docker-nginx#adding-custom-nginx-modules - We still haven't added this module yet to NGINX by default though.

**Comment by mamiu** [comment]
@mtogiz Just use this directory for FastCGI cache: `/opt/bitnami/nginx/tmp/fastcgi/cache`. It has the correct permissions, so you won't get any permission errors.

So your first line should look something like this:

```nginx
fastcgi_cache_path /opt/bitnami/nginx/tmp/fastcgi/cache levels=1:2 keys_zone=WHATAEVER_KEYZONE_NAME_HERE:100m inactive=60m;
```

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
