### ISSUE TITLE
Nginx not compiled with --with-threads argument to the configure command

### ISSUE THREAD

**Issue by kriptor** [bitnami/bitnami-docker-wordpress-nginx#36]
Hi,

is there a particular reason for nginx not being compiled with thread pool support?
Would it be possible to include this nginx feature in the near future?

Thx

**Comment by juan131** [comment]
Hi @kriptor 

Thanks so much for your feedback!! We don't see any cons on adding support for this feature. Therefore, we'll release a new revision of NGINX (and WP+NGINX) adding this flag to the compilation recipe.

I'll notify you once the new revision are released.

**Comment by juan131** [comment]
Hi @kriptor 

We just release bitnami/nginx (versions **1.19.4-debian-10-r6** and **1.18.0-debian-10-r170**) including the flag. See:

```console
$ docker run --rm -it bitnami/nginx:1.19.4-debian-10-r6 nginx -V
...
configure arguments: --prefix=/opt/bitnami/nginx --with-http_stub_status_module --with-stream --with-http_gzip_static_module --with-mail --with-http_realip_module --with-http_v2_module --with-http_ssl_module --with-mail_ssl_module --with-http_gunzip_module --with-threads --with-http_auth_request_module --with-http_sub_module --with-http_geoip_module --add-module=/bitnami/blacksmith-sandox/nginx-module-vts-0.1.18 --add-dynamic-module=/bitnami/blacksmith-sandox/nginx-module-geoip2-3.3.0 --add-module=/bitnami/blacksmith-sandox/nginx-module-substitutions-filter-0.20190806.0 --add-module=/bitnami/blacksmith-sandox/nginx-module-brotli-0.20201006.0
```

And we also release bitnami/wordpress-nginx (version **5.5.3-debian-10-r3**).

I proceed to close this issue. Feel free to reopen it if you continue running into issues.
