### ISSUE TITLE
Custom Image

### ISSUE THREAD

**Issue by proboxdev** [bitnami/bitnami-docker-wordpress-nginx#37]
Hi, I'm following the tutorial provided here https://docs.bitnami.com/tutorials/deploy-locally-custom-wordpress/ and at Step 3, it states to add this line to app-entrypoint.sh  "nami_initialize apache php mysql-client wordpress" what is the equivalent line when customising the nginx image?

Thanks

**Comment by javsalgar** [comment]
Hi,

Here you can see the equivalent command: https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/rootfs/app-entrypoint.sh

```
    nami_initialize php nginx mysql-client wordpress
```

**Comment by proboxdev** [comment]
Thanks for that. 

I've run the build successfully however when running docker-compose up it fails during the wordpress initialization on the 7th plugin listed. At first I thought I had an issue with one of my plugins but when I removed it from the install it stopped on the next plugin with this error: 

Warning: The 'PLUGIN-NAME' plugin could not be found.
wordpress_1  | Error: No plugins activated.

All the plugins are downloaded by the download-extra.sh file.

How do I find the logs as to whether or not they were all unzipped and moved?

Thanks

**Comment by javsalgar** [comment]
Hi,

You could add more debugging in the `download-extra.sh` script to see if one of the commands failed. For example, you could add `set -e` at the beginning of the script. That would make the script fail if one of the commands went wrong.

**Comment by proboxdev** [comment]
Appreciate your help, fixed the issue.

During the docker build process this happens: bitnami-pkg unpack wordpress-5.5.3-6 --checksum 1c2b4f65ddc7a4c003ce319ed51ea5739d151e121b020cf45f6f74ebfbabdfaa

I assume that is a base wordpress source code package, I would like to replace that or remove the plugins it contains as I don't need any of those plugins and it would be easier to remove them or not have them during the build process, how can I achieve that? 

I've looked for anything relating to that package in the repo but nothing exists.

Thanks again.

**Comment by javsalgar** [comment]
Hi,

My advice would be to add a step in the dockerfile where you remove any plugin you don't want. Would that work for you?

**Comment by proboxdev** [comment]
Hi, 

Thanks, I tried a very dirty way of doing it by using the download-extra script which worked. I'll do it via Dockerfile whhen I've sorted other issues.

rm -R /opt/bitnami/wordpress/plugins
mkdir /opt/bitnami/wordpress/plugins

I built an image and when deploying the container has this error:
Error executing 'postInstallation': PHP Parse error:  syntax error, unexpected 'w3' (T_STRING), expecting ')' in /opt/bitnami/wordpress/wp-config.php on line 29

I then tried to deploy the bitnami image pulled directly from docker.io which also throws the sam error.

image:
  registry: docker.io
  repository: bitnami/wordpress-nginx
  tag: 5.5.3-debian-10-r31

How do I find out what is on line 29 inside that image at the point it fails? 

Thanks for your help.

**Comment by marcosbc** [comment]
Hi @proboxdev, you could try to run the container image with a custom CMD, i.e.:

    docker run -ti my_wp_ngx bash

And then once you're inside the Bash console, run the entrypoint:

    /app-entrypoint.sh /run.sh

Once it fails, you will be able to read the contents of wp-config.php, i.e.:

    cat /opt/bitnami/wordpress/wp-config.php

**Comment by proboxdev** [comment]
Hi, it was the password for the DB, it doesn't like certain characters even though they are supported by MySQL and work in a traditional wordpress deployment, the docker process must parse the characters differently.

Which now brings me to this error: Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/wordpress/wp-content' -> '/opt/bitnami/wordpress/wp-content'nami   

I've searched for that and it brings up mention of overlayfs drivers however my K8S cluster doesn't use it. I can't find anything else relevant. Any ideaas?

**Comment by juan131** [comment]
HI @proboxdev 

How did you reproduce that error? Could you specify the exact steps?
Did you run `/app-entrypoint.sh /run.sh` twice?

**Comment by proboxdev** [comment]
Hi, thanks for all your help,

After building a custom image I deployed it to a scaleway kubernetes cluster using the bitnami wordpress helm chart via kubeapps by replacing the image it pulled.

Watching the logs using the image debug the wordpress initialisation process stops at this point during the process:

[prepareDataToPersist] Preparing /opt/bitnami/wordpress/wp-content to persist in /bitnami/wordpress/wp-contentwordpre TRACE [prepareDataToPersist] Preparing /opt/bitnami/wordpress/wp-config.php to persist in /bitnami/wordpress/wp-config.php

It then re-initialises and hits the file already exists error. Then the container simply enters a continual reboot process stopping at the file exists error each time.

The only changes I have made to the build is to add plugins and one theme by following the blogs bitnami provide. I have re-run the customisation several times mirroring  the  bitnami repo and pushing to a new repo to track all changes I made to ensure I only changed what the blog said I should do.

I assume those two scripts are running more than once as each initialisation starts: 

wordpre INFO  Preparing WordPress environment
wordpre DEBUG Running installation script

Thanks

**Comment by juan131** [comment]
Hi @proboxdev 

Could you share the exact **Dokerfile** and **download-extra.sh** you're using at this very moment? Please feel free to remove any sensitive information the script might contain before sharing it.

**Comment by jfeliweb** [comment]
Hi! I am running into the same error as @proboxdev when trying to run my custom image
``Error executing ‘postInstallation’: EEXIST: file already exists, symlink ‘/bitnami/wordpress/wp-content’ -> ‘/opt/bitnami/wordpress/wp-content’``

I followed the same blog post and created a **download-extra.sh**
```
#!/bin/bash
set -e

# Start removing Bitnami Default Plugins
rm -rf /opt/bitnami/wordpress/wp-content/plugins/akismet/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/all-in-one-seo-pack/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/all-in-one-wp-migration/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/wp-cloud-mgmt-console/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/google-analytics-for-wordpress/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/jetpack/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/simple-tags/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/amp/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/wordpress-mu-domain-mapping/
rm -f /opt/bitnami/wordpress/wp-content/plugins/hello.php

# Start removing Default Themes
rm -rf /opt/bitnami/wordpress/wp-content/themes/twenty*

# Grab and Install Fracture Core Plugin and Theme
curl -sL -C - -H 'Authorization: token <token>' https://github.com/github/core-plugin/archive/1.0.zip -o /tmp/core-plugin.zip
curl -sL -C - -H 'Authorization: token <token>' https://github.com/github/theme/archive/1.0.zip -o /tmp/theme.zip

unzip /tmp/core-plugin.zip -d /opt/bitnami/wordpress/wp-content/plugins
mv -f /opt/bitnami/wordpress/wp-content/plugins/core-plugin-1.0 "/opt/bitnami/wordpress/wp-content/plugins/core-plugin/"
unzip /tmp/theme.zip -d /opt/bitnami/wordpress/wp-content/themes
mv -f /opt/bitnami/wordpress/wp-content/themes/theme-1.0 "/opt/bitnami/wordpress/wp-content/themes/theme/"
rm -rf /tmp/core-plugin.zip
rm -rf /tmp/theme.zip

# Grab and install other plugins

curl -o /tmp/wordpress-seo.15.6.2.zip https://downloads.wordpress.org/plugin/wordpress-seo.15.6.2.zip
curl -o /tmp/stream.3.6.0.zip https://downloads.wordpress.org/plugin/stream.3.6.0.zip
curl -o /tmp/wp-redis.1.1.1.zip https://downloads.wordpress.org/plugin/wp-redis.1.1.1.zip
curl -o /tmp/jwt-auth.zip https://downloads.wordpress.org/plugin/jwt-auth.zip
curl -o /tmp/svg-support.2.3.18.zip https://downloads.wordpress.org/plugin/svg-support.2.3.18.zip
curl -o /tmp/user-switching.1.5.6.zip https://downloads.wordpress.org/plugin/user-switching.1.5.6.zip

unzip /tmp/wordpress-seo.15.6.2.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/stream.3.6.0.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/wp-redis.1.1.1.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/jwt-auth.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/svg-support.2.3.18.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/user-switching.1.5.6.zip -d /opt/bitnami/wordpress/wp-content/plugins

rm -rf /tmp/wordpress-seo.15.6.2.zip
rm -rf /tmp/stream.3.6.0.zip
rm -rf /tmp/wp-redis.1.1.1.zip
rm -rf /tmp/jwt-auth.zip
rm -rf /tmp/svg-support.2.3.18.zip
rm -rf /tmp/user-switching.1.5.6.zip

## S3 Uploads
curl -sL -C - -H 'Authorization: token <token>' https://github.com/humanmade/S3-Uploads/releases/download/2.2.1/manual-install.zip -o /tmp/manual-install.zip
unzip /tmp/manual-install.zip -d /opt/bitnami/wordpress/wp-content/plugins/s3-uploads/
rm -rf /tmp/manual-install.zip
```
As the blog post described I add the run command under `COPY rootfs / ` in the **Dockerfile**
```
RUN bash fracture-init.sh
```
And I am activating the plugins in the app-entrypoint.sh
```
#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/run.sh" ]]; then
    . /nginx-init.sh
    . /wordpress-init.sh
    nami_initialize php nginx mysql-client wordpress
    info "Starting gosu... "
    . /post-init.sh
fi

nami_initialize nginx php mysql-client wordpress
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate fracture_theme'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate fracture_core_plugin'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate jwt-auth'
#su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate s3-uploads'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate stream'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate svg-support'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate user-switching'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate w3-total-cache'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wordpress-seo'
info "Starting wordpress... "

exec tini -- "$@"
```
Everything works fine locally but not when I add my custom image to the WordPress Helm Chart I am now getting this: 
```
Error executing ‘postInstallation’: EEXIST: file already exists, symlink ‘/bitnami/wordpress/wp-content’ -> ‘/opt/bitnami/wordpress/wp-content’
```
Any help or if I could get pointed in the right direction would be greatly appreciated.

**Comment by juan131** [comment]
HI @jfeliweb 

The WP+NGINX images is by default a non-root container (in other words it's executed with a non-privileged user), see:

- https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/Dockerfile#L76

Did you take that into account when customizing your image? I see you're running actions such as `su daemon -s ...` that will not work when running the container as non-root.

Please also check that the Helm chart executes the containers as non-root by default (although it can be adapted):

- https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml#L299

Could you share the Dockerfile you're using?

---

Tip for you bash scripts: use loops (or even better xargs):

```bash
plugins=(
    "fracture_theme"
    "fracture_core_plugin"
    "jwt-auth"
    "s3-uploads"
    
)
printf "%s\n" "${plugins[@]}" | xargs -P0 -I@ /opt/bitnami/wp-cli/bin/wp theme activate @
```

**Comment by jfeliweb** [comment]
Hi @juan131 
> The WP+NGINX images is by default a non-root container (in other words it's executed with a non-privileged user), see:
> 
> * https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/Dockerfile#L76
> 
> Did you take that into account when customizing your image? I see you're running actions such as `su daemon -s ...` that will not work when running the container as non-root.
> 

Under step 2 of the Bitnami tutorial, it states to "Remove the USER 1001 directive to be able to launch the container as root user so your Dockerfile"

- [https://docs.bitnami.com/tutorials/deploy-locally-custom-wordpress/](https://docs.bitnami.com/tutorials/deploy-locally-custom-wordpress/)


> Please also check that the Helm chart executes the containers as non-root by default (although it can be adapted):
> 
> * https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml#L299
> 

The helm chart is executing the container as non-root by default and I would like to keep it this way so I will have to figure out how to make the adjustments.

> Could you share the Dockerfile you're using?
> 

Here is my **Dockerfile**:
```
FROM docker.io/bitnami/minideb:buster
LABEL maintainer "Bitnami <containers@bitnami.com>"

ENV BITNAMI_PKG_CHMOD="-R g+rwX" \
    HOME="/" \
    PATH="/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/wp-cli/bin:/opt/bitnami/nginx/sbin:/opt/bitnami/mysql/bin:/opt/bitnami/common/bin:/opt/bitnami/nami/bin:$PATH"

COPY prebuildfs /
# Install required system packages and dependencies
RUN install_packages ca-certificates curl gzip libaudit1 libbsd0 libbz2-1.0 libc6 libcap-ng0 libcom-err2 libcurl4 libexpat1 libffi6 libfftw3-double3 libfontconfig1 libfreetype6 libgcc1 libgcrypt20 libgeoip1 libglib2.0-0 libgmp10 libgnutls30 libgomp1 libgpg-error0 libgssapi-krb5-2 libhogweed4 libicu63 libidn2-0 libjemalloc2 libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 liblcms2-2 libldap-2.4-2 liblqr-1-0 libltdl7 liblzma5 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmcrypt4 libmemcached11 libmemcachedutil2 libncurses6 libnettle6 libnghttp2-14 libonig5 libp11-kit0 libpam0g libpcre3 libpng16-16 libpq5 libpsl5 libreadline7 librtmp1 libsasl2-2 libsqlite3-0 libssh2-1 libssl1.1 libstdc++6 libsybdb5 libtasn1-6 libtidy5deb1 libtinfo6 libunistring2 libuuid1 libx11-6 libxau6 libxcb1 libxdmcp6 libxext6 libxml2 libxslt1.1 libzip4 procps sudo tar unzip zlib1g
RUN /build/bitnami-user.sh
RUN /build/install-nami.sh
RUN bitnami-pkg unpack php-7.4.14-1 --checksum deab46bf8aa3b80307657c86a721960e1ce7f8f5b51aad0578c594012912d08d
RUN bitnami-pkg install wp-cli-2.4.0-2 --checksum 33c3b53e87e9e433291ac3511e68263c80b43aa4de3dead9502934f506b7f2e6
RUN bitnami-pkg unpack nginx-1.18.0-7 --checksum 0c798efa4673cd0fc90742889f96a052d43683f92c524a258dd62427eff7d475
RUN bitnami-pkg unpack mysql-client-10.3.27-0 --checksum f96905e763a6334b75a7cdb07f8d89658cde02be41cb09d91d0682fc649fdcff
RUN bitnami-pkg unpack wordpress-5.6.0-6 --checksum 4e2436ae11c65a0e17999e33829b9ebcbc3f0d8bf4ff2d15b9fd0c44e52a5096
RUN bitnami-pkg install tini-0.19.0-1 --checksum 9b1f1c095944bac88a62c1b63f3bff1bb123aa7ccd371c908c0e5b41cec2528d
RUN bitnami-pkg install gosu-1.12.0-2 --checksum 4d858ac600c38af8de454c27b7f65c0074ec3069880cb16d259a6e40a46bbc50
RUN apt-get update && apt-get upgrade -y && \
    rm -r /var/lib/apt/lists /var/cache/apt/archives
RUN ln -sf /dev/stdout /opt/bitnami/nginx/logs/access.log
RUN ln -sf /dev/stderr /opt/bitnami/nginx/logs/error.log

COPY rootfs /
RUN bash download-extra.sh
ENV ALLOW_EMPTY_PASSWORD="no" \
    BITNAMI_APP_NAME="wordpress-nginx" \
    BITNAMI_IMAGE_VERSION="5.6.0-debian-10-r39" \
    MARIADB_HOST="mariadb" \
    MARIADB_PORT_NUMBER="3306" \
    MARIADB_ROOT_PASSWORD="" \
    MARIADB_ROOT_USER="root" \
    MYSQL_CLIENT_CREATE_DATABASE_NAME="" \
    MYSQL_CLIENT_CREATE_DATABASE_PASSWORD="" \
    MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES="ALL" \
    MYSQL_CLIENT_CREATE_DATABASE_USER="" \
    MYSQL_CLIENT_ENABLE_SSL="no" \
    MYSQL_CLIENT_SSL_CA_FILE="" \
    NAMI_PREFIX="/.nami" \
    NGINX_ENABLE_CUSTOM_PORTS="no" \
    NGINX_HTTPS_PORT_NUMBER="8443" \
    NGINX_HTTP_PORT_NUMBER="8080" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-10" \
    OS_NAME="linux" \
    PHP_MEMORY_LIMIT="256M" \
    PHP_OPCACHE_ENABLED="yes" \
    SMTP_HOST="" \
    SMTP_PASSWORD="" \
    SMTP_PORT="" \
    SMTP_PROTOCOL="" \
    SMTP_USER="" \
    SMTP_USERNAME="" \
    WORDPRESS_BLOG_NAME="User's Blog!" \
    WORDPRESS_DATABASE_NAME="bitnami_wordpress" \
    WORDPRESS_DATABASE_PASSWORD="" \
    WORDPRESS_DATABASE_SSL_CA_FILE="" \
    WORDPRESS_DATABASE_USER="bn_wordpress" \
    WORDPRESS_EMAIL="user@example.com" \
    WORDPRESS_EXTRA_WP_CONFIG_CONTENT="" \
    WORDPRESS_FIRST_NAME="FirstName" \
    WORDPRESS_HTACCESS_OVERRIDE_NONE="yes" \
    WORDPRESS_HTACCESS_PERSISTENCE_ENABLED="no" \
    WORDPRESS_HTTPS_PORT="8443" \
    WORDPRESS_HTTP_PORT="8080" \
    WORDPRESS_LAST_NAME="LastName" \
    WORDPRESS_PASSWORD="bitnami" \
    WORDPRESS_RESET_DATA_PERMISSIONS="no" \
    WORDPRESS_SCHEME="http" \
    WORDPRESS_SKIP_INSTALL="no" \
    WORDPRESS_TABLE_PREFIX="wp_" \
    WORDPRESS_USERNAME="user"

EXPOSE 8080 8443

ENTRYPOINT [ "/app-entrypoint.sh" ]
CMD [ "/run.sh" ]
```


> Tip for you bash scripts: use loops (or even better xargs). Example:
> 
> ```shell
> plugins=(
>     "fracture_theme"
>     "fracture_core_plugin"
>     "jwt-auth"
>     "s3-uploads"
>     ...
> )
> printf "%s\n" "${plugins[@]}" | xargs -P0 -I@ /opt/bitnami/wp-cli/bin/wp theme activate @
> ```

Thank you for the tip I will make the adjustment!

**Comment by juan131** [comment]
Hi @jfeliweb 

Let's try a different approach: instead of editing the original Dockerfile, let's extend the current image (as explained in [this guide](
https://github.com/bitnami/bitnami-docker-wordpress-nginx#extend-this-image)). 

1. In your working directory, create a structure like the one below:

```
$ tree .
.
├── Dockerfile
└── scripts
   ├── build
   │   ├── download-plugins.sh
   │   └── remove-default-plugins.sh
   └── initialize
       └── activate-plugins.sh

3 directories, 4 files
```

2. The Dockerfile should look like this (see the comments):

```Dockerfile
FROM bitnami/wordpress-nginx:latest
LABEL maintainer "Juan Ariza <juanariza@vmware.com>"

## Change user to perform privileged actions
USER 0

## Copy build scripts to /tmp
COPY scripts/build/* /tmp/
## Scripts mounted at /docker-entrypoint-init.d/ are executed 
## after WordPress initialization
COPY scripts/initialize/* /docker-entrypoint-init.d/

## Execute build scripts
RUN chmod +x /tmp/*.sh /docker-entrypoint-init.d/*.sh && \
    /tmp/remove-default-plugins.sh && \
    /tmp/download-plugins.sh && \
    rm /tmp/remove-default-plugins.sh /tmp/download-plugins.sh

## Revert to the original non-root user
USER 1001
```

3. Create a **remove-default-plugins.sh** script similar to this one:

```bash
#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

plugins_directory="/opt/bitnami/wordpress/wp-content/plugins/"
themes_directory="/opt/bitnami/wordpress/wp-content/themes/"
default_plugins=(
    "amp"
    "akismet"
    "all-in-one-seo-pack"
    "all-in-one-wp-migration"
    "google-analytics-for-wordpress"
    "jetpack"
    "simple-tags"
    "wordpress-mu-domain-mapping"
    "wp-cloud-mgmt-console"
)
default_themes=(
    "twentynineteen"
    "twentytwenty"
    "twentytwentyone"
)
printf "%s\n" "${default_plugins[@]}" | xargs -P0 -I@ rm -rf "${plugins_directory:?}/@"
printf "%s\n" "${default_themes[@]}" | xargs -P0 -I@ rm -rf "${themes_directory:?}/@"
```

4. Create a **download-plugins.sh** script similar to this one:

```bash
#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

wp_download_url="https://downloads.wordpress.org"
plugins_directory="/opt/bitnami/wordpress/wp-content/plugins/"
themes_directory="/opt/bitnami/wordpress/wp-content/themes/"
plugins=(
    "jwt-auth"
    "stream.3.6.0"
    "svg-support.2.3.18"
    "user-switching.1.5.6"
    "wordpress-seo.15.6.2"
    "wp-redis.1.1.1"
)
themes=(
    "urbane.1.0.6"
)
printf "%s\n" "${plugins[@]}" | xargs -P0 -I@ curl -o "/tmp/@.zip" "${wp_download_url}/plugin/@.zip"
printf "%s\n" "${plugins[@]}" | xargs -P0 -I@ unzip "/tmp/@.zip" -d "$plugins_directory"
printf "%s\n" "${plugins[@]}" | xargs -P0 -I@ rm "/tmp/@.zip"
find "$plugins_directory" -type d -exec chmod 775 {} \;
find "$plugins_directory" -type f -exec chmod 664 {} \;
printf "%s\n" "${themes[@]}" | xargs -P0 -I@ curl -o "/tmp/@.zip" "${wp_download_url}/theme/@.zip"
printf "%s\n" "${themes[@]}" | xargs -P0 -I@ unzip "/tmp/@.zip" -d "$themes_directory"
printf "%s\n" "${themes[@]}" | xargs -P0 -I@ rm "/tmp/@.zip"
find "$themes_directory" -type d -exec chmod 775 {} \;
find "$themes_directory" -type f -exec chmod 664 {} \;

```

5. Create a **activate-plugins.sh** script similar to this one:

```bash
#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

plugins=(
    "jwt-auth"
    "stream"
    "svg-support"
    "user-switching"
    "wordpress-seo"
    "wp-redis"
)
printf "%s\n" "${plugins[@]}" | xargs -P0 -I@ /opt/bitnami/wp-cli/bin/wp plugin activate @
/opt/bitnami/wp-cli/bin/wp theme activate urbane
```

6. Finally build your custom WP:

```console
$ docker build . -t my-custom-wp
```

**Comment by jfeliweb** [comment]
@juan131 Thank you for the detailed help!

I didn't notice at first but the WordPress Helm Chart ran the Apache webserver version while I was trying to run an NGINX. I just switch to Apache and everything ran smoothly.

Also, I was able to add the private plugins and themes.

**Comment by juan131** [comment]
Great! Glad to hear that @jfeliweb 
I proceed to close the issue again, do not hesitate to let us know if you require further help.
