### ISSUE TITLE
TTFB & Amplify 

### ISSUE THREAD

**Issue by siddjellali** [bitnami/bitnami-docker-wordpress-nginx#39]
Hi team, 

I have some TTFB issue with your image and i would like install amplify, but it's not compatible with external container yet.
https://github.com/nginxinc/docker-nginx-amplify

Are you manage to deploy amplify as a default component ?
Am i the only one to have TTFB issue ? >1sec

Thanks

**Comment by carrodher** [comment]
I was reviewing old issues in GitHub and there are no more cases related to TTFB, are you facing this issue only in this Wordpress with nginx container, or if you deploy the regular Wordpress (the apache based one) are you also facing the same issue? just to discard networking issues non-related to the container itself.

About adding new components, [here](https://github.com/bitnami/bitnami-docker-wordpress-nginx#extend-this-image) you can find more information about how you can customize and extend the Wordpress with nginx image to solve different use cases.

**Comment by siddjellali** [comment]
Appreciate your answer ! I will proceed.
There are no big gap 0.2sec between regular wordpress and yours, Issue seems located on my server.
Thanks.
