### ISSUE TITLE
Theme upload results in „413 Request Entity Too Large“

### ISSUE THREAD

**Issue by JanSichula** [bitnami/bitnami-docker-wordpress-nginx#4]
Hello,

I was excited to find your image and use it first for my local development needs. Yet here is the issue where I need some help. When I try to upload my theme as a ZIP package that is some 2MB large, it results in „413 Request Entity Too Large“. Please, how should I properly configure NGINX for larger uploads with this image.

**Comment by andresbono** [comment]
Hi @JanSichula, you should add a new directive in the _nginx_ configuration file. Add the following line to http context to increase the size limit:

`/opt/bitnami/nginx/conf/nginx.conf`
```
...

http {
    client_max_body_size 20M;

...
```

Then, reload the container.

Note that you may want to persist the configuration file so the changes in the file are maintained between container restarts.

Let us know if it works.
