### ISSUE TITLE
How to run wordpress in a subdirectory

### ISSUE THREAD

**Issue by Shivam9268** [bitnami/bitnami-docker-wordpress-nginx#44]
**Description**

I want to run Wordpress in a directory. Eg: http://example.com/subdirectory/
I am currently able to run the site correctly if I update the `wp-config.php` file and set:
```
define( 'WP_HOME', 'http://example.com/subdirectory/' );
define( 'WP_SITEURL', 'http://example.com/subdirectory/' );
```

But login and admin portals are not working correctly. The links there still map to `http://example.com/wp-admin/plugins.php` and not `http://example.com/subdirectory/wp-admin/plugins.php`

**Comment by Shivam9268** [comment]
We started using multisite configuration.

**Comment by juan131** [comment]
I'm glad you were able to achieve your needs using WP Multisite.
