### ISSUE TITLE
Instructions to get this image running on Azure Web App with Azure MySQL (with SSL)

### ISSUE THREAD

**Issue by rmhaustralia** [bitnami/bitnami-docker-wordpress-nginx#45]
Hey Bitnami,

Are you able to provide instructions on how to get this image to run as a container on Azure, specifically with Azure MySQL with SSL? I've tried numerous methods (Docker Compose, adding Application settings, etc) but can't seem to make any solid progress (I'd like to host a website, not become a DevOps Engineer .. lol).

Cheers, Simon.

**Comment by miguelaeh** [comment]
Hi @rmhaustralia ,
In order to connect to an external database it should be enough by editing the env vars described at https://github.com/bitnami/bitnami-docker-wordpress-nginx#database-connection-configuration. Then, to configure the database that will be created you can edit the env vars at https://github.com/bitnami/bitnami-docker-wordpress-nginx#create-a-database-for-wordpress-using-mysql-client

Could you describe the errors you are getting?

**Comment by rmhaustralia** [comment]
After doing more reading, I think I'll be able to work out the basics, but the issues I don't have my head around.

- Azure Web Apps have the ability to have persistent storage in /home ... How can I have the bitnami WordPress install and nginx configurations to be in the /home directory.
- Azure only allows a single external port. What needs to be configured to enable SSH through the Azure Portal.

It's a pity Microsoft doesn't maintain their images.

**Comment by miguelaeh** [comment]
Hi @rmhaustralia ,
> Azure Web Apps have the ability to have persistent storage in /home ... How can I have the bitnami WordPress install and nginx configurations to be in the /home directory.

You could give a try to set `WORDPRESS_VOLUME_DIR` to `/home` in order to configure the persistence directory into the container. 

> Azure only allows a single external port. What needs to be configured to enable SSH through the Azure Portal. 

About this, I am not sure which is the problem you are facing with it. Can't you just use the SSH port of Nginx?

**Comment by rmhaustralia** [comment]
Hey @miguelaeh 

Looking at https://docs.microsoft.com/en-us/azure/app-service/tutorial-multi-container-app, I think I have the wordpress path covered with (correct?), in so far as it will map the /bitnami/wordpress directory to the web app persistent storage (correct?):

volumes:
  - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/bitnami/wordpress

I'll build the image tomorrow, and let you know how I go with this, and ssh.

**Comment by rmhaustralia** [comment]
In regards to an external MySQL server, are these the only environment variables I need to change to get that working (if encryption is disabled on the MySQL server)?

WORDPRESS_DATABASE_HOST
WORDPRESS_DATABASE_PORT_NUMBER
WORDPRESS_DATABASE_USER
WORDPRESS_DATABASE_NAME
WORDPRESS_DATABASE_PASSWORD

**Comment by pablogalegoc** [comment]
Hi @rmhaustralia!

Those should be the variables you need to set to get the database working. Regarding the volumes, remember that this is a non-root container, so the mounted files and directories must have the proper permissions for the UID 1001.

**Comment by rmhaustralia** [comment]
Hey,
I've resolved this by learning how, and then building a container to suit my needs.
Thanks,
