### ISSUE TITLE
Wordpress-nginx as helm deployment

### ISSUE THREAD

**Issue by govindkailas** [bitnami/bitnami-docker-wordpress-nginx#46]
**Description**

Can we have a helm chart based on wordpress-nginx image? I tried using this image on the helm chart here https://github.com/bitnami/charts/tree/master/bitnami/wordpress
But this seems to be breaking the UI.

**Steps to reproduce the issue:**

1. In the helm chart https://github.com/bitnami/charts/tree/master/bitnami/wordpress, updated the image URL to `wordpress-nginx`  (this helm chart is using Wordpress - Apache)
2. Mentioned the ingress URL and annotation, left the remaining configuration as it is.

**Describe the results you received:**

Wordpress UI is scrambled 

![Untitled](https://user-images.githubusercontent.com/6698224/125794451-5d2b5881-3dbf-4056-bb6c-2c17183756c5.jpg)

**Describe the results you expected:**

To show the default Wordpress UI

I'm trying to make this work as a helm deployment, it would be really great if there are some guidelines on deploying this as a  helm chart.

**Comment by marcosbc** [comment]
Hi @govindkailas, unfortunately I have been unable to reproduce your issue. Note that the `wordpress-nginx` image is expected to work perfectly fine with those settings.

In my case, I deployed it like this:

```
$ helm install my-wp --set service.type=LoadBalancer --set image.repository=bitnami/wordpress-nginx --set image.tag=5.7.2-debian-10-r52 .
```

Once deployed, I `exec`ed into the WordPress pod and verified that it contained NGINX:

```
$ which nginx
/opt/bitnami/nginx/sbin/nginx
```

And the website shows fine:

![Screen Shot 2021-07-16 at 13 37 31](https://user-images.githubusercontent.com/5102866/125941835-01e29043-b86c-45a0-8475-5d94d828f503.png)

Please try that deployment command and let us know if you see anything different. It would also help if you could share the specific deployment commands that you used.

**Comment by govindkailas** [comment]
One difference that I could spot is, I have exposed service as `ClusterIP`. I have an Ingress too. The screenshot I posted is while accessing it using the https ingress hostname.

**Comment by govindkailas** [comment]
I can confirm that it's working with `LoadBalancer` not sure what's going wrong when I try `Ingress`. Is it working for you as `Ingress`

**Comment by migruiz4** [comment]
Hi @govindkailas,

Could you please check your browser's console logs? Maybe there we can find some significant errors or warnings that help us troubleshoot this issue.

**Comment by govindkailas** [comment]
I see all the assets calls are going to `HTTP` endpoint instead of`HTTPS` that's the reason for failure.
![image](https://user-images.githubusercontent.com/6698224/126119809-2a0f9f17-2376-4d6a-bb75-7c62ab740886.png)

I have enabled `https` via `ingress annotation`

**Comment by migruiz4** [comment]
Hi @govindkailas ,

To have Wordpress serving the content using HTTPS when connected via Ingress with TLS, you can set the following value:
```yaml
wordpressExtraConfigContent: |
  if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) \&\& $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
    $_SERVER['HTTPS'] = 'on';
  }
```

This way, Wordpress will serve on HTTPS when the header HTTP_X_FORWARDED_PROTO equals 'https', and will use HTTP when not.

Source: https://wordpress.org/support/topic/wp-behind-reverse-proxy-all-content-insecure/

**Comment by govindkailas** [comment]
Thanks @migruiz4,  I will give this a try and let you know.

**Comment by govindkailas** [comment]
This is revolved now, I see all the assets are loading with `HTTPS` 👍
