### ISSUE TITLE
WordPress 5.8 released

### ISSUE THREAD

**Issue by mashirozx** [bitnami/bitnami-docker-wordpress-nginx#47]
**Description**

https://wordpress.org/support/wordpress-version/version-5-8/

There need a upgrade of WordPress. Thanks!

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alvneiayu** [comment]
hi @mashirozx 

Thanks a lot for noticing us the new version. We are already compiling and preparing the container for the new version. Our team are working on it.

Thanks a lot again

Álvaro

**Comment by mashirozx** [comment]
Thanks for your work！

**Comment by mashirozx** [comment]
Thanks for your work！

**Comment by alvneiayu** [comment]
thanks to you!
