### ISSUE TITLE
How can I pass environment variables of an external database in docker-compos?

### ISSUE THREAD

**Issue by SergeyPichugin** [bitnami/bitnami-docker-wordpress-nginx#48]
Hi!
link to your docker compass https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/docker-compose.yml

I have a problem I want to connect to an external database, but the problem is that using your docker compos file and running it, the environment variables are not thrown into the wp-config.php file ((tell me does it work at all?

I checked this by running the image, I changed the value of the standard environment variables, but they did not change in the wp-config.php file

please tell me what to do?

**Comment by alvneiayu** [comment]
hi @SergeyPichugin 

Using those env vars, you can connect your wordpress with an external database:

- WORDPRESS_DATABASE_HOST
- WORDPRESS_DATABASE_PORT_NUMBER
- WORDPRESS_DATABASE_USER
- WORDPRESS_DATABASE_NAME
- WORDPRESS_DATABASE_PASSWORD

Could you share with me your docker-compose and logs, please?

Thanks a lot

Álvaro

**Comment by SergeyPichugin** [comment]
@alvneiayu Hi!
Here are the container logs
`Attaching to sravnipromoservice_wordpress_1

wordpress_1 | wordpress 15:51:51.99

wordpress_1 | wordpress 15:51:51.99 Welcome to the Bitnami wordpress-nginx container

wordpress_1 | wordpress 15:51:51.99 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx

wordpress_1 | wordpress 15:51:52.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues

wordpress_1 | wordpress 15:51:52.00

wordpress_1 | wordpress 15:51:52.01 INFO ==> ** Starting WordPress setup **

wordpress_1 | wordpress 15:51:52.03 INFO ==> Validating settings in NGINX_* env vars

wordpress_1 | wordpress 15:51:52.05 INFO ==> Initializing NGINX

wordpress_1 | wordpress 15:51:52.08 INFO ==> Configuring PHP options

wordpress_1 | wordpress 15:51:52.08 INFO ==> Setting PHP max_input_time option

wordpress_1 | wordpress 15:51:52.11 INFO ==> Validating settings in MYSQL_CLIENT_* env vars

wordpress_1 | wordpress 15:51:52.35 INFO ==> Restoring persisted WordPress installation

wordpress_1 | wordpress 15:51:53.91 INFO ==> Trying to connect to the database server

wordpress_1 | Error: 'wp-config.php' not found.

wordpress_1 | Either create one manually or use `wp config create`.


sravnipromoservice_wordpress_1 exited with code 1`

and file content docker-compose.yml
`version: '2'
services:
  wordpress:
    image: docker.io/bitnami/wordpress-nginx:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './wp-content/:/bitnami/wordpress'    
    environment:
        - WORDPRESS_SKIP_BOOTSTRAP=yes
        - WORDPRESS_DATABASE_HOST=127.0.0.1
        - WORDPRESS_DATABASE_PORT_NUMBER=3306
        - WORDPRESS_DATABASE_USER=login
        - WORDPRESS_DATABASE_PASSWORD=password
        - WORDPRESS_DATABASE_NAME=example
        - ALLOW_EMPTY_PASSWORD=no
        - PHP_MAX_INPUT_TIME=240`
all necessary plugins and themes are in the folder which I copy to the container folder bitnami/wordpress

**Comment by alvneiayu** [comment]
hi @SergeyPichugin 

I think that you are not having problem with the variables. I think that you are having problem with the permissions in the folder wp-content or with the volumes. Are you cleaning the volumes? (docker-compose down -v)

Thanks a lot

Álvaro

**Comment by SergeyPichugin** [comment]
Thank you @alvneiayu ! yes, the problem is really not in the variables, but when I try to copy my content to vp-content, it will throw the same error (I can't understand why this is

`Attaching to sravnipromoservice_wordpress_1

wordpress_1 | wordpress 09:42:24.23

wordpress_1 | wordpress 09:42:24.23 Welcome to the Bitnami wordpress-nginx container


wordpress_1 | wordpress 09:42:24.24 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx

wordpress_1 | wordpress 09:42:24.24 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues

wordpress_1 | wordpress 09:42:24.24

wordpress_1 | wordpress 09:42:24.25 INFO ==> ** Starting WordPress setup **

wordpress_1 | wordpress 09:42:24.27 INFO ==> Validating settings in NGINX_* env vars

wordpress_1 | wordpress 09:42:24.28 INFO ==> Initializing NGINX

wordpress_1 | wordpress 09:42:24.31 INFO ==> Configuring PHP options

wordpress_1 | wordpress 09:42:24.31 INFO ==> Setting PHP max_input_time option

wordpress_1 | wordpress 09:42:24.34 INFO ==> Validating settings in MYSQL_CLIENT_* env vars

wordpress_1 | wordpress 09:42:24.54 INFO ==> Restoring persisted WordPress installation

wordpress_1 | wordpress 09:42:26.70 INFO ==> Trying to connect to the database server

wordpress_1 | Error: 'wp-config.php' not found.

wordpress_1 | Either create one manually or use `wp config create`.


sravnipromoservice_wordpress_1 exited with code 1`

**Comment by alvneiayu** [comment]
hi @SergeyPichugin 

Delete the volumes, change the permissions to your wp-content (chmod 777 wp-content) and then try to do the docker-compose up.

I think that you are having problems with the permissions in your folder.

Thanks a lot

Álvaro

**Comment by SergeyPichugin** [comment]
@alvneiayu 
I changed the permissions in the wp-content folders, but unfortunately this did not solve the problem(

-rw-r--r--  1 sergey  staff  587  5 авг 12:56 docker-compose.yml
drwxr-xr-x  7 sergey  staff  224 11 июл 21:03 documents
**drwxrwxrwx**  9 sergey  staff  288 11 июл 21:03 wp-content

docker log remained the same(

wordpress_1  | wordpress 09:56:55.51 
wordpress_1  | wordpress 09:56:55.53 Welcome to the Bitnami wordpress-nginx container
wordpress_1  | wordpress 09:56:55.55 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx
wordpress_1  | wordpress 09:56:55.57 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues
wordpress_1  | wordpress 09:56:55.58 
wordpress_1  | wordpress 09:56:55.61 INFO  ==> ** Starting WordPress setup **
wordpress_1  | wordpress 09:56:55.73 INFO  ==> Validating settings in NGINX_* env vars
wordpress_1  | wordpress 09:56:55.80 INFO  ==> Initializing NGINX
wordpress_1  | wordpress 09:56:55.99 INFO  ==> Configuring PHP options
wordpress_1  | wordpress 09:56:56.01 INFO  ==> Setting PHP max_input_time option
wordpress_1  | wordpress 09:56:56.20 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars

wordpress_1  | wordpress 09:56:57.48 INFO  ==> Restoring persisted WordPress installation
wordpress_1  | wordpress 09:56:58.76 INFO  ==> Trying to connect to the database server

wordpress_1  | Error: 'wp-config.php' not found.
wordpress_1  | Either create one manually or use `wp config create`.

I think I'm stumped((

**Comment by alvneiayu** [comment]
hi @SergeyPichugin 

Let me investigate a little bit, no problem. Could you do me a favor, please? Test with the original docker-compose, just to discard that it is a problem with the environment. I am going to test with your docker-compose. I will come back as soon as possible

Thanks a lot

Álvaro

**Comment by alvneiayu** [comment]
hi @SergeyPichugin 

This is a non-root container, could you test to modify the user of your folder to 1001, please?

```
sudo chown 1001:1001 -R wp-content
```

Thanks a lot

Álvaro

**Comment by javsalgar** [comment]
Hi,

Could you confirm that the wp-content folder is mounted in /bitnami/wordpress/wp-content and not /bitnami/wordpress itself? That could explain the issue

**Comment by Goro2030** [comment]
Hola Javier! Hi! 

The wp.content folder is in '/opt/bitnami/apps/wordpress/htdocs/wp-content'

**Comment by Jimcumming** [comment]
I've run into the same issue when trying to create a local dev environment for my users. I wanted to create a docker-compose that would map in a directory from the host, into the /wp-content/themes folder, It looks as if the install routine thinks that if there is anything at all in /bitnami/wordpress then there is an existing installation which should be restored. It might be better if it just checks for a wp-config.php instead.

**Comment by javsalgar** [comment]
This sounds interesting, including @marcosbc so he can provide some insight as the developer of the bash logic.

**Comment by javsalgar** [comment]
For the time being, i would try mounting the wp-content folder to /opt/bitnami/wordpress/. I think that should bypass the persistence check

**Comment by marcosbc** [comment]
You should be able to mount `/opt/bitnami/wordpress/wp-content` directly, however you would need to make sure that `WORDPRESS_DATA_TO_PERSIST` does not include that folder (note that it defaults to `wp-config.php wp-content`).
