### ISSUE TITLE
How to add SSL certificate to wordpress server block in nginx conf for this image?

### ISSUE THREAD

**Issue by akailash** [bitnami/bitnami-docker-wordpress-nginx#5]
What is the elegant way of adding SSL certificate using this image? I am trying to access my domain with https://<domain_name> and it lands at the nginx default page. On checking the nginx configuration in this image, I find that the wordpress server block only points to port 80. Since this path is not persistent(not part of docker volume), what is the best method to change this so that the block listens on both 80 and 443?

```
root@f55fb7b7fea4:/# cat /opt/bitnami/nginx/conf/vhosts/wordpress-vhosts.conf 
server {
  listen 0.0.0.0:80;
  server_name myapp.example.com;

  root /opt/bitnami/wordpress;
  index index.php;

  location / {
    try_files $uri $uri/ /index.php?q=$uri&$args;
  }

  if (!-e $request_filename)
  {
    rewrite ^/(.+)$ /index.php?q=$1 last;
  }

  location ~ \.php$ {
    fastcgi_pass localhost:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }
}
```

**Comment by akailash** [comment]
Ah... Sorry about this... Finally saw the file in the volumes section of docker-compose

**Comment by gcsecsey** [comment]
@akailash I'm also trying to add SSL certificates to my image, but hadn't succeeded so far, can you help me please? After persisting the `wordpress-vhosts.conf` file, do I only have to paste the block for port 80 for port 443 as well? Is there any other modifications needed for the config?

**Comment by juan131** [comment]
Some correction

> Since this path is not persistent (not part of docker volume)

Minor correction. This path is being persisted (see https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-9/docker-compose.yml#L18) when using the `docker-compose.yml`.

@gcsecsey you can clone the repo, modify the [wordpress-vhosts.conf](https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-9/wordpress-vhosts.conf) as you desire and run `docker-compose up`:

```
$ git clone https://github.com/bitnami/bitnami-docker-wordpress-nginx
$ cd bitnami-docker-wordpress-nginx/4/debian-9
$ vim wordpress-vhosts.conf # use the editor you prefer
$ docker-compose up
```

**Comment by gcsecsey** [comment]
@juan131 thank you for the instructions, will try!

**Comment by juan131** [comment]
Great @gcsecsey !!!
Please do not hesitate to let us know if you face any issue.

**Comment by Stra1ghtarrow** [comment]
Hi,

I've tried following the steps above on the latest image but I seem to struggling. The only config file available is wordpress-server-block.conf.

After adding the ssl cert locations to the config I receive this error:

Cannot start service wordpress: driver failed programming external connectivity on endpoint debian-10_wordpress_1 (b5fa697c5f103e052bdef8fbb0d35788125720ad8062d66dd535b5fe4685fcd7): Bind for 0.0.0.0:443 failed: port is already allocated
Is there something I'm missing here?

thanks

**Comment by juan131** [comment]
Hi @akailash 

I guess you have another service in your computer using the port 443, therefore, the conflict when docker tries to bind that port. Please double-check there isn't any service using that port on your computer, or use a different port in the **docker-compose.yaml**

**Comment by Stra1ghtarrow** [comment]
Hi thanks for getting back to me. It seems to be the default nginx page. Is it possible to disable this and route it back to the WP site?

**Comment by juan131** [comment]
Hi @akailash 

I guess you just need to revert the changes so your server block looks like the original one, see https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/wordpress-server-block.conf
