### ISSUE TITLE
Issue passing data into WORDPRESS_EXTRA_WP_CONFIG_CONTENT

### ISSUE THREAD

**Issue by Jimcumming** [bitnami/bitnami-docker-wordpress-nginx#51]
I'm in the process of setting up a new system which runs Wordpress sites on ECS Fargate containers. This system is being constructed using Terraform to build the infrastructure and we use the bitnami-docker-wordpress-nginx image as the base container image. 

In order to make the site behave properly behind a load balancer we need to set the HTTPS variable based on the X_FORWARDED_PROTO header. We also need to run some WP CLI scripts post install and to make WP CLI work correctly on EC2 we also need to set the HTTP_HOST variable. This page https://make.wordpress.org/cli/handbook/guides/common-issues/#php-notice-undefined-index-on-_server-superglobal suggests the code to use for these issues. 

`if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO'] ) {
  $_SERVER['HTTPS']='on';
}

if ( defined( 'WP_CLI' ) && WP_CLI && ! isset( $_SERVER['HTTP_HOST'] ) ) {
    $_SERVER['HTTP_HOST'] = 'example.com';
}`

We also need to define WP_CACHE = true and FORCE_SSL_ADMIN = true. As a result the final json encoded code we need to insert via the WORDPRESS_EXTRA_WP_CONFIG_CONTENT variable is  

`"define('WP_CACHE', true);\ndefine('FORCE_SSL_ADMIN', true);\nif ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO'] ) {\n  $_SERVER['HTTPS']='on';\n}\nif ( defined( 'WP_CLI' ) && WP_CLI && ! isset( $_SERVER['HTTP_HOST'] ) ) {\n    $_SERVER['HTTP_HOST'] = 'example.com';\n}"`

If I pass this code via a docker-compose.yml file I need to escape the && to` \&\&` and the $ to $$ to make things work. 

However when I'm using the same code to create a container definition in Terraform, this escaping doesn't work. Removing the escaping for && and $ stops it throwing json validation errors. But in start up the containers throws the following issue. 

PHP Parse error: syntax error, unexpected '$_SERVER' (T_VARIABLE) in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 176

Is there another method of adding to the wp-config.php file to add this code. It seems to me that passing anything complex via an environment variable is fraught with issues, especially when you have to encode the value to pass through from a config file through Terraform and into ECS and maintain valid PHP. Or am I missing something obvious?

**Comment by Jimcumming** [comment]
Just a quick update on this. I see that I don't need to define the HTTP host for WP CLI requests as this is already being handled in the WP CLI request, so I'll remove that and try again.

**Comment by marcosbc** [comment]
Hi @Jimcumming, first of all, it seems like the logic you mentioned should actually be included in the current WordPress configuration. During the refactor, it seems like we did not port it and hence it was not properly added. We are going to work on adding it, so that use cases like yours are supported.

That said, in the meantime, it should be possible for you to mount a file with the contents you mentioned, and then specify the path in `WORDPRESS_EXTRA_WP_CONFIG_CONTENT_FILE`. Then [the logic](https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/wordpress-env.sh#L83) will detect this variable and set `WORDPRESS_EXTRA_WP_CONFIG_CONTENT` with the appropriate contents.

**Comment by marcosbc** [comment]
Hi @Jimcumming, it should be possible for you to mount a file with the contents you mentioned, and then specify the path in `WORDPRESS_EXTRA_WP_CONFIG_CONTENT_FILE`. Then [the logic](https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/wordpress-env.sh#L83) will detect this variable and set `WORDPRESS_EXTRA_WP_CONFIG_CONTENT` with the appropriate contents.

**Comment by Jimcumming** [comment]
Thank you, I wasn't aware of the _file functionality, That should help out in a lot of places.
