### ISSUE TITLE
How can I migrate from a non Docker host to Bitnami Docker?

### ISSUE THREAD

**Issue by farzadrabiee** [bitnami/bitnami-docker-wordpress-nginx#53]
Hello,

I have 5+ WordPress websites that need to migrate to Docker. The current host doesn’t use Docker.

How can I export the config of php.ini, Nginx and etc to the new Docker?

Thanks

**Comment by javsalgar** [comment]
Hi,

From my experience, the option that caused me the least pain was to use a WordPress migration plugin such as the All-in-one migration plugin. About the php settings, could you check if these env vars work for you? https://github.com/bitnami/bitnami-docker-wordpress-nginx/#php-configuration

**Comment by mamiu** [comment]
@farzadrabiee I think this is more a question for sites like Stackoverflow. Anyway, just use a WordPress plugin like Updraft to backup the whole WordPress website (you have to do it for every website separately). Then just restore the backups in the new dockerized WordPress environments. If you haven't setup Docker then either use a hosting provider that offers docker hosting or install docker on your own server. If you wanna use your own server create a directory for each website and put a docker-compose.yaml file in it like the one in this repository. Start it for every website with `docker-compose up -d` (make sure they're listening on different ports). If you want you can route traffic to these websites with solutions like [Traefik](https://traefik.io/), [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy), etc. If you wanna do it large scale, learn Kubernetes.

**Comment by farzadrabiee** [comment]
Thank you so much for your reply @javsalgar and @mamiu
