### ISSUE TITLE
Disable absolute_redirect in the nginx configuration by default

### ISSUE THREAD

**Issue by mamiu** [bitnami/bitnami-docker-wordpress-nginx#54]
**Description**

If this docker image is used in a cluster or on a server which hosts multiple different applications / services (which I assume is the case for most people), then it's very likely that the container sits behind a router, an additional reverse proxy or something like this. But as soon as there's an additional routing layer in between the container and the client where the port on the router / reverse proxy / etc. doesn't match the port of the container, the default nginx [`absolute_redirect on;`](http://nginx.org/en/docs/http/ngx_http_core_module.html#absolute_redirect) setting is causing redirect issues.

**For example:**

Let's assume this docker image is used to run a WordPress nginx docker container on a server like this:

```
                                     ┌─── Server ─────────────────────────────────────┐
                                     │                                                │
                                     │                 ┌────────┐    ┌────────┐       │
                                     │                 │        │    │        │       │
                                     │            ┌────┤  App1  │    │  App2  │       │
 ┌────────────────┐          ┌───────┴────────┐   │    │        │    │        │       │
 │                │          │                ├───┘    └────────┘    └───┬────┘       │
 │                │          │                │                          │            │
 │   The client   ├──────────┤     Router     ├──────────────────────────┘            │
 │ (e.g. Browser) │          │ (e.g. Traefik) │                                       │
 │                │          │                ├───┐                                   │
 └────────────────┘          └───────┬────────┘   │    ┌───────────────────────────┐  │
                                     │            │    │                           │  │
                                     │            └────┤  Bitnami Wordpress Nginx  │  │
                                     │                 │                           │  │
                                     │                 └───────────────────────────┘  │
                                     │                                                │
                                     └────────────────────────────────────────────────┘
```

The "Bitnami Wordpress Nginx" container is listening on port **8080** and port **8443**.  
The [Traefik](https://traefik.io/) router is listening on port **80** and port **443** to route http and https requests into the cluster.   
Let's say we configured our router to route traffic to the domain http://www.example.com/ to port 8080 of the "Bitnami Wordpress Nginx" container. Everything will be working fine until nginx inside the "Bitnami Wordpress Nginx" container triggers a client redirect. That happens for example if the client requests the URL http://www.example.com/wp-admin (without a slash at the end). Nginx will then redirect the client (with a 301 response) not to http://www.example.com/wp-admin/ (this time with a slash at the end) but to http://www.example.com:8080/wp-admin/ (with a the **8080** port in the URL). We could tell nginx not to add the port in the redirect with `port_in_redirect off;` which would even work in this example, but not if someone is hosting it on a specific port other than 80 or 443. E.g. if our router listened on port 1234 instead of 80 / 443 then the WordPress website could be accessed with http://www.example.com:1234. But as soon as a redirect happens nginx will delete the port from the redirected URL (because it doesn't know anything about the port 1234 of the router). So a request to http://www.example.com:1234/wp-admin wouldn't be redirected to http://www.example.com:1234/wp-admin/ but to http://www.example.com/wp-admin/ (without the port).

The solution to all of this is to add [`absolute_redirect off;`](http://nginx.org/en/docs/http/ngx_http_core_module.html#absolute_redirect) to the nginx server configuration. Then the `Location` header field in the 301 response is just `/wp-admin/` instead of the full URL.

**Steps to reproduce the issue:**

1. Create a `docker-compose.yaml` like this one (make sure the ports in the port mapping of the **wordpress** service are different):

```yaml
version: "3"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: bitnami/wordpress-nginx:latest
    ports:
      - "1234:8080"
    volumes:
      - "wordpress_data:/bitnami/wordpress"
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
volumes:
  mariadb_data:
  wordpress_data:
```

2. Start the WordPress application with `docker-compose up -d`.
3. Go to the browser and check if the application is up and running: http://localhost:1234/
4. If it is, open the following URL (without a slash at the end!): http://localhost:1234/wp-admin

**Describe the results you received:**

With the steps above you'll get redirected to http://localhost:8080/wp-admin/

**Describe the results you expected:**

You should have been getting redirected to http://localhost:1234/wp-admin/

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 11
  Running: 3
  Paused: 0
  Stopped: 8
 Images: 26
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.807GiB
 Name: docker-desktop
 ID: 36X4:5ZEJ:JZ4K:PJVB:4XDR:NFCQ:MRHM:M225:CWDB:EKBR:IDGB:PGZU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I've tried it with Docker for Mac (see docker info above) and on a [k3s](https://k3s.io/) (v1.21.2+k3s1 on ubuntu server 20.10) kubernetes cluster.

**Comment by juan131** [comment]
Hi @mamiu 

Thanks so much for bringing up this issue and such a well-described context. We could enable relative redirects in the default NGINX configuration file, see:

- https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/rootfs/opt/bitnami/nginx/conf/nginx.conf

Or enable it in the specific server blocks used to server WordPress that are based in the template below:

-  https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/wordpress/bitnami-templates/nginx-wordpress-basic.conf.tpl

In any case, I agree we have an issue here and redirections aren't working as expected. I'd like @rafariossaa and @marcosbc to confirm if they agree with enabling relative redirects or there are cons on this approach I'm not aware of.

**Comment by mamiu** [comment]
@juan131 My pleasure!

I assume that this area might be the right place:
https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/rootfs/opt/bitnami/nginx/conf/nginx.conf#L13-L39

**Comment by marcosbc** [comment]
Hi, we have an internal task for investigating redirection issues with both Apache and NGINX container images, when running a container through a Docker/Ingress proxy on a non-standard port.

For NGINX it seems like disabling absolute redirects could be a possible solution, but unfortunately not for Apache (there is no such option).

We would like the configuration for both web servers to be similar, so I'm not yet sure if this is the best way to go for NGINX, as in the end we would deviate from the standard NGINX conf.

In the meantime while we investigate this, you can mount a file to `/opt/bitnami/nginx/conf/server_blocks/` which contains the line `absolute_redirect off;`. That configuration would be applied globally to the `http` block, and allow you to get it working for now in your deployment.

**Comment by mamiu** [comment]
Thanks @marcosbc that's what I'm doing currently until this is fixed / improved.

> We would like the configuration for both web servers to be similar, so I'm not yet sure if this is the best way to go for NGINX, as in the end we would deviate from the standard NGINX conf.

I totally understand your point, but there's technically no other option than relative redirects because the nginx server within the "Bitnami Wordpress Nginx" container has no chance to know the port of the proxy / router (except you would introduce a config / setting / environment variable to tell the container the outer port).

Thank you both for your fast responses!

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.

**Comment by fmulero** [comment]
Hi @mamiu, a new version of bitnami/wordpress-nginx has been released (`bitnami/wordpress-nginx:5.8.3-r14`) disabling by default the directive `absolute_redirect `.  This configuration can be managed as explained in the [container documention](https://github.com/bitnami/bitnami-docker-wordpress-nginx#user-and-site-configuration). You can find more details about how it works in [bitnami/nginx](https://github.com/bitnami/bitnami-docker-nginx#solving-redirection-issues)

**Comment by mamiu** [comment]
@fmulero Awesome! Thank you so much, highly appreciate it!

Just out of interest: I thought this repository is no longer actively maintained. Who's now in charge and who's working on updates like these?

**Comment by fmulero** [comment]
As @carrodher said,  [Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution) since this asset was marked as a “Community supported solution”.

This particular issue was affecting several bitnami containers and some of them are actively maintained.

**Comment by mamiu** [comment]
I see. Great to hear that fixes and/or improvements from other (actively maintained) dependency projects are still getting pushed to the non-maintained projects. 👍
