### ISSUE TITLE
How to Wordpress Nginx Docker can use https behind AWS Application Load Balancer

### ISSUE THREAD

**Issue by khanhcd92** [bitnami/bitnami-docker-wordpress-nginx#56]
Description

I have setup a running Wordpress application on ECS Fargate and it behind AWS Application Load Balancer.
SSL Terminate on Application Load  Balancer.  I have set some variables in environment of ECS Fargate as
- WORDPRESS_ENABLE_HTTPS: true

My issue is: when I access with my https domain then css, js still using http link. UI was broken. So How can I fix that?

Console error log
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS.
```

Thank you!

**Comment by khanhcd92** [comment]
Hi @alvneiayu 

Thank you for your support.

About (1), It works.
https://gist.github.com/wgroenewold/68fcaaabfbf939282b1a5cddd6f636e8

About (2), I have checked document. I saw that WORDPRESS_EXTRA_WP_CONFIG_CONTENT variable when setting to run docker. So Could I add below config to it ?

```
define('FORCE_SSL_ADMIN', true);
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https'){
 $_SERVER['HTTPS']='on';
}
```

About (3), I will check it.

**Comment by alvneiayu** [comment]
hi @khanhcd92 

I think so. You must be able to include the configuration using the env var WORDPRESS_EXTRA_WP_CONFIG_CONTENT. [Here](https://github.com/bitnami/bitnami-docker-wordpress/issues/318) you can find another GH case that maybe you can take a look also.

Thanks a lot

Álvaro

**Comment by khanhcd92** [comment]
Hi @alvneiayu 

Many thanks for your support.

I have a last question. I want to override path for wordpress link or custom sub folder for wordpress without using multi site for wordpress.
How could I custom it with wordpress docker nginx?

Example:

Current: 
- https://domain/page_name
- https://domain/2021/08/03/post_name

Expect: 
- https://domain/wp-blog/page_name
- https://domain/wp-blog/2021/08/03/post_name

**Comment by alvneiayu** [comment]
hi @khanhcd92 

Maybe those urls can help you a little bit about this:

https://docs.bitnami.com/ibm/infrastructure/nginx/administration/create-custom-application-php/
https://docs.bitnami.com/bch/infrastructure/nginx/configuration/create-vhost-nginx/

Thanks a lot

Álvaro

**Comment by khanhcd92** [comment]
Many thanks @alvneiayu 

I do not have any questions. So I will close this issue.

**Comment by alvneiayu** [comment]
hi @khanhcd92 

thanks to you and happy to help

Álvaro
