### ISSUE TITLE
Add a file on the worpdress root

### ISSUE THREAD

**Issue by aana5i** [bitnami/bitnami-docker-wordpress-nginx#57]
**Description**

I would like to add a file on rhe root of worpdress but i don't find a way to do it.
I did a try by adding them in the persistant volume but i got a 404 error when i try to reach them

**Steps to reproduce the issue:**

1. Install mariadb and the wordpress using persistant volumes
2. copy the files in the persistant volume
3. got to the site url and try to open the ***.php file

**Describe the results you received:**

404 file not found error

**Describe the results you expected:**

Open the ***.php file

**Additional information you deem important (e.g. issue happens only occasionally):**

Followed the guide using persistance volume and `docker run -d ...`

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:08 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:16 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1055-aws
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 978.6MiB
 Name: ip-172-31-21-128
 ID: 55J2:A2JA:BLFE:3UJT:YNRH:Z7IN:YDMY:3QQD:NK7H:C7AZ:WUZB:33QH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
AWS EC2

**Comment by randradas** [comment]
Hi @aana5i have you checked once the container is running that the file is there?

**Comment by aana5i** [comment]
Files are in the /wordpress folder on the running container. At the same place as wp-content.
But its only wp-content/ folder and wp-config files on this location. 
Its why i would like to know if its the good location and where is the good location ?

**Comment by randradas** [comment]
Hello @aana5i, my thoughts on this are:
- Every document under the wordpress documentroot should be accessible in a typical-ish web server configuration.
- Check the webserver virtualhost configuration. it shouldn't contain anything doing stranger things when you try to access something that is not expected like a custom .php file added by you. I mean something like a redirections and so on.

Another thing I would check is wordpress documentation in order to be sure the Wordpress product is not preventing you to access non-default wodpress php files.

Also:
- have you checked the webserver logs? they could show useful information
- what are the custom .php file permissions?

**Comment by aana5i** [comment]
Thanks @randradas can you tell me the wordpress documentroot on the bitnami image please ?
Because i think its the problem, i find a folder who may not be the documentroot

**Comment by randradas** [comment]
it is set in this file: https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/wordpress-server-block.conf

`root /opt/bitnami/wordpress;`

**Comment by aana5i** [comment]
thanks
