### ISSUE TITLE
Error establishing database connection when using getenv to dynamically set database config in persisted wp-config.php

### ISSUE THREAD

**Issue by lotaezhao** [bitnami/bitnami-docker-wordpress-nginx#62]
**Description**

When using this container the database connection configuration is not able to be set using getenv within a persisted wp-config.php, it has to be hardcoded in the wp-config.php beforehand. It is best practice when running Wordpress on cloud services that you don't hardcode any parameters. All environment specific parameters should to be passed dynamically to the application at runtime.

If I start the container with an external database configured via environment variables but use the default wordpress installation Wordpress works as expected. However, on inspection the database configuration has been hardcoded inside the wp-config.php during the first initialization. 

This doesn't happen when you use a persisted wordpress installation though. When I use an external database with a persisted wordpress installation (mounted to /bitnami/wordpress) wordpress is not able to connect to the database and throws "Error establishing a database connection". This is despite the wp-config.php being configured to set the database configuration via getenv from the environment variables that the container is using. The container seems to be resetting the environment variables that are exposed to wordpress so that you can't use getenv inside wp-config.php.

If I hardcode database configuration values in the persisted wp-config.php it works. But the point is that I don't want these to be hardcoded. I will be running this container on Azure App Service and need to pass the database configuration to wordpress dynamically.

I think this is a common enough scenario that it should be supported as part of the base container image. In the meantime can you please advise how this behavior can be modified? I have looked into the container image and there are a myriad of setup scripts that are called during startup so it's not easy to decipher where the changes need to go to enable this.

**Steps to reproduce the issue:**

1. Import existing wordpress database on external mysql server
2. Configure database connection parameters to be set from the container environment variables by adding these lines in the persisted wp-config.php:
```
// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */

$connectstr_dbhost = getenv('WORDPRESS_DATABASE_HOST');
$connectstr_dbname = getenv('WORDPRESS_DATABASE_NAME');
$connectstr_dbusername = getenv('WORDPRESS_DATABASE_USER');
$connectstr_dbpassword = getenv('WORDPRESS_DATABASE_PASSWORD');

define('DB_NAME', $connectstr_dbname);

/** MySQL database username */
define('DB_USER', $connectstr_dbusername);

/** MySQL database password */
define('DB_PASSWORD', $connectstr_dbpassword);

/** MySQL hostname */
define('DB_HOST', $connectstr_dbhost);
```
3. Run bitnami/wordpress-nginx container and connect to external database with persisted wordpress installation:
```
docker container run -d \
--name bitnami-wp -p 8080:8080 \
--network my_network \
--volume /path/to/wordpress-persistence:/bitnami/wordpress \
--env WORDPRESS_DATABASE_HOST=mysql \
--env WORDPRESS_DATABASE_PORT_NUMBER=3306 \
--env WORDPRESS_DATABASE_NAME=mydatabase \
--env WORDPRESS_DATABASE_USER=myuser \
--env WORDPRESS_DATABASE_PASSWORD=mypassword \
--env WORDPRESS_SKIP_BOOTSTRAP=yes \
bitnami/wordpress-nginx:latest
```

**Describe the results you received:**

When you load the Wordpress website it throws error "Error establishing a database connection"

**Describe the results you expected:**

The docker environment variables should be available to the persisted wp-config.php so they can be dynamically set using getenv and Wordpress should work!

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:22 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.771GiB
 Name: docker-desktop
 ID: U2JY:VNRR:XWKT:QXZ7:65LT:I2Q7:BQAO:C75R:JRPR:2JU3:7ZTG:WCGV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alemorcuq** [comment]
I've been investigating and this is happening due to some PHP FPM config: the 'clear-env' directive: https://www.php.net/manual/en/install.fpm.configuration.php#clear-env

This is set by default to 'yes'. I have tested setting it to 'no' instead and PHP was able to read the environment variables.

**Comment by lotaezhao** [comment]
@alemorcuq Thanks for update, I had searched for 'clear_env' but couldn't find where in the this image it is defined. It wasn't in the php.ini, where did you find it?

**Comment by alemorcuq** [comment]
You can mount a file to `/opt/bitnami/php/etc/common.conf`  with that directive set and it will be loaded to the default `www` pool defined in `/opt/bitnami/php/etc/php-fpm.d/www.conf`.

**Comment by yongzhang** [comment]
> You can mount a file to `/opt/bitnami/php/etc/common.conf` with that directive set and it will be loaded to the default `www` pool defined in `/opt/bitnami/php/etc/php-fpm.d/www.conf`.

looks it doesn't work, I also tried `/opt/bitnami/php/etc/php-fpm.d/custom.conf`, still no luck.

**Comment by Kiogora** [comment]
This root cause of this issue has also been experienced when setting up an initial wordpress install using environment variables.

**Comment by miguelaeh** [comment]
Hi guys, could please share the errors you are getting after setting the parameter that @alemorcuq said?

**Comment by yongzhang** [comment]
> Hi guys, could please share the errors you are getting after setting the parameter that @alemorcuq said?

Please see my issue comment here: https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/67#issuecomment-973914793, I still see the same behavior after added `clear_env = no`, I was starting the container the first time on existing database and `wp-content`.

**Comment by miguelaeh** [comment]
Please check this: https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/67#issuecomment-976340363
