### ISSUE TITLE
How to build a mirror image on the arm processor？

### ISSUE THREAD

**Issue by guvmao** [bitnami/bitnami-docker-wordpress-nginx#64]

**Comment by miguelaeh** [comment]
Hi, unfortunately, ARM is not a supported architecture at this moment.
We created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, this way we can funnel all the conversation in a single place regarding ARM64 support.
We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
