### ISSUE TITLE
Unable to make redirect request

### ISSUE THREAD

**Issue by pnthai88** [bitnami/bitnami-docker-wordpress-nginx#65]
Hello,
i tried to mount:
`- ./h3/bitnami_wp_conf.conf:/opt/bitnami/nginx/conf/bitnami/extend.conf`

#extend.conf
```
# WebP Express rules
# --------------------
location ~* ^/?wp-content/.*\.(png|jpe?g)$ {
add_header Vary Accept;
expires 365d;
if ($http_accept !~* "webp"){
    break;
}
try_files
    /wp-content/webp-express/webp-images/doc-root/$uri.webp
    $uri.webp
    /wp-content/plugins/webp-express/wod/webp-on-demand.php?xsource=x$request_filename&wp-content=wp-content
    ;
}

# Route requests for non-existing webps to the converter
location ~* ^/?wp-content/.*\.(png|jpe?g)\.webp$ {
    try_files
    $uri
    /wp-content/plugins/webp-express/wod/webp-realizer.php?xdestination=x$request_filename&wp-content=wp-content
    ;
}
# ------------------- (WebP Express rules ends here)
```

With this config, and it's not working. How I can modify Nginx configuration? Thank you!

**Comment by Mauraza** [comment]
Hi @pnthai88,

Could you tell us who are you deploying WordPress? If you are using a docker-compose, could you share it?

Maybe these part of the README.md could you help you https://github.com/bitnami/bitnami-docker-nginx#configuration

**Comment by pnthai88** [comment]
> Hi @pnthai88,
> 
> 
> 
> Could you tell us who are you deploying WordPress? If you are using a docker-compose, could you share it?
> 
> 
> 
> Maybe these part of the README.md could you help you https://github.com/bitnami/bitnami-docker-nginx#configuration
> 
> 

Thank you,
I tried it and work perfectly.
The problem is at; i put config it wrong config file.
Need to be in /server_blocks/

**Comment by Mauraza** [comment]
Hi @pnthai88,

I'm glad you solve the problem!
