### ISSUE TITLE
missing /opt/bitnami/ folder

### ISSUE THREAD

**Issue by djzen** [bitnami/bitnami-docker-wordpress-nginx#66]
I want to edit server blocks. However I cant seem to find `/opt/bitnami/`

Documentation obviously says there is `/opt/bitnami` but I really cant find it via SFTP
 
```
cd /opt/bitnami
-bash: cd: /opt/bitnami: No such file or directory
```

What I did was install docker & docker compose in a new Ubuntu 18 image.
And then, I installed this bitnami docker WordPress from these instructions https://hub.docker.com/r/bitnami/wordpress-nginx

```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress-nginx/master/docker-compose.yml
$ docker-compose up
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```

Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~18.04.3
 Built:             Mon Nov  1 01:04:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~18.04.3
  Built:            Fri Oct 22 00:57:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.5-0ubuntu3~18.04.1
  GitCommit:
 runc:
  Version:          1.0.1-0ubuntu2~18.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

- Output of `docker info`:

```

Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-136-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.852GiB
 Name: ecs-e202
 ID: 4R6O:FNJC:CUSZ:UVSO:O5T2:ABR3:SXGR:4YSW:JZLZ:LBX7:2O6Y:WL7Z
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Kiogora** [comment]
I am subscribed to this repository feed and looks like the reason you cant access is because the docker image filesystem is separate from your host filesystem. As such, you cant access /opt/bitnami by SFTP as that location because it doesnt exist, but it does exist on the docker filesystem.

You should persist your server blocks by mounting a host directory - that hosting your server block .conf files - as a volume. This is well documented at the "adding custom server blocks" within the repository README.

Have a further look at the main nginx default configuration https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/rootfs/opt/bitnami/nginx/conf/nginx.conf to see how your server blocks will be included/sourced.

**Comment by juan131** [comment]
Hi @djzen 

As @Kiogora mentioned you're not inside the container filesystem, you previously need to access it (for instance, using [docker-compose exec](https://docs.docker.com/compose/reference/exec)).

In any case, I guess you're referring to the documentation for the Bitnami VM(s) nor the container docs. To obtain info about how to use this container, please refer to the README.md below:

- https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/README.md
