### ISSUE TITLE
Error establishing database connection when not persisting wp-config.php

### ISSUE THREAD

**Issue by p10trk** [bitnami/bitnami-docker-wordpress-nginx#67]
**Description**

If configured to persist some data, but not wp-config.php, WordPress is unable to connect to the database. It seems the default wp-config.php is used, where database host is not set, or is set to localhost.

**Steps to reproduce the issue:**

1. Start a MySQL server on the host
2. Start the container like this
```
docker container run -d --rm -p 8080:8080 \
--volume $PWD/wordpress-data:/bitnami/wordpress \
--env WORDPRESS_DATABASE_HOST=<host's IP address> \
--env WORDPRESS_DATABASE_PORT_NUMBER=3306 \
--env WORDPRESS_DATABASE_NAME=dbname \
--env WORDPRESS_DATABASE_USER=dbuser \
--env WORDPRESS_DATABASE_PASSWORD=secret \
--env WORDPRESS_SKIP_BOOTSTRAP=yes \
--env WORDPRESS_DATA_TO_PERSIST="uploads" \
--env WORDPRESS_EXTRA_WP_CONFIG_CONTENT="define('UPLOADS', 'uploads');" \
--env BITNAMI_DEBUG="true" \
bitnami/wordpress-nginx:5.8.2
```
3. Check the container's logs
`docker logs <container ID>`

**Describe the results you received:**

The container logs show:
```
wordpress 17:31:56.78 
wordpress 17:31:56.78 Welcome to the Bitnami wordpress-nginx container
wordpress 17:31:56.78 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx
wordpress 17:31:56.78 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues
wordpress 17:31:56.78 
wordpress 17:31:56.79 INFO  ==> ** Starting WordPress setup **
wordpress 17:31:56.80 INFO  ==> Validating settings in NGINX_* env vars
wordpress 17:31:56.80 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory
wordpress 17:31:56.80 DEBUG ==> Updating NGINX configuration based on environment variables
wordpress 17:31:56.82 INFO  ==> Configuring PHP options
wordpress 17:31:56.82 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 17:31:56.85 DEBUG ==> Validating settings in WORDPRESS_* environment variables...
wordpress 17:31:56.86 WARN  ==> Hostname db could not be resolved, this could lead to connection issues
wordpress 17:31:56.90 INFO  ==> Restoring persisted WordPress installation
wordpress 17:31:56.91 INFO  ==> Trying to connect to the database server
wordpress 17:31:56.91 DEBUG ==> Getting DB_NAME from WordPress configuration
wordpress 17:31:57.05 DEBUG ==> Getting DB_USER from WordPress configuration
wordpress 17:31:57.12 DEBUG ==> Getting DB_PASSWORD from WordPress configuration
wordpress 17:31:57.20 DEBUG ==> Getting DB_HOST from WordPress configuration
wordpress 17:31:57.27 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2002 (HY000): Can't connect to MySQL server on 'localhost' (99)
wordpress 17:32:02.29 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2002 (HY000): Can't connect to MySQL server on 'localhost' (99)
```

The container stops eventually.

EDIT:
Starting the container without persistence (`--env WORDPRESS_DATA_TO_PERSIST=" "`) alone doesn't change the outcome. Oddly enough, after removing the volume, WordPress is able to connect to the database.

**Describe the results you expected:**

The container is able to connect to the database on the correct address.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time.

**Version**

- Output of `docker version`:

```
Client:
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Sun Oct 10 22:41:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Fri Oct  8 00:00:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.7
  GitCommit:        
 runc:
  Version:          1.0.2
  GitCommit:        c42bf99-dirty
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 286
 Server Version: 20.10.9
 Storage Driver: btrfs
  Build Version: Btrfs v5.14.1 
  Library Version: 102
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: c42bf99-dirty
 init version: 
 Security Options:
  seccomp
   Profile: default
  selinux
  cgroupns
 Kernel Version: 5.14.16-301.fc35.x86_64
 Operating System: Fedora Linux 35 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.03GiB
 Name: fedora
 ID: 222Y:FUBH:YNKP:PJ3F:DJCS:26PW:YK52:OOCX:Q63O:WL3V:UTSL:NANH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

SELinux is in permissive mode.

**Comment by yongzhang** [comment]
I have the same issue

**Comment by Mauraza** [comment]
Hi @p10trk,

It seems you have a problem connecting to the database. 
```logs
wordpress 17:31:57.27 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2002 (HY000): Can't connect to MySQL server on 'localhost' (99)
```

If you want to connect to a database that is in localhost, could you try to add the following flag:
```bash
--add-host=host.docker.internal:host-gateway
```

**Comment by yongzhang** [comment]
in my case I set `WORDPRESS_DATA_TO_PERSIST = "wp-content"`, I want `wp-config.php` to be created dynamically, but I can see only `wp-content` in `/bitnami/wordpress` path, no `wp-config.php` generated.

**Comment by p10trk** [comment]
Hi @Mauraza,

`WORDPRESS_DATABASE_HOST` is set to the IP address of the host in my LAN, which is 10.200.0.23. So WordPress shouldn't be attempting to connect to localhost.

**Comment by yongzhang** [comment]
> Hi @Mauraza,
> 
> `WORDPRESS_DATABASE_HOST` is set to the IP address of the host in my LAN, which is 10.200.0.23. So WordPress shouldn't be attempting to connect to localhost.

yeah the same issue, looks like the container didn't pick up values from env vars. I guess https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/62 is the same issue.

**Comment by Mauraza** [comment]
Hi @p10trk and @yongzhang,

If it's the same issue we continue the conversation in #62, to avoid having duplicate open issues.

**Comment by miguelaeh** [comment]
Hi,
From what I understood, you are using a volume with already initialized data that has not the `wp-config.php` file. This does not seem to be an issue, but how all our images actually work.
The database configuration is written to the `wp-config.php` file in the first initialization of the container. You did not persist that file so your database configuration was not persisted. Since the image will only re-configure the `wp-config.php` when the application is not initialized (i.e. the volume is empty) and in your case it already has data, the database configuration will not be set again into the `wp-config.php` file.
You can check that logic [here](https://github.com/bitnami/bitnami-docker-wordpress/blob/e57d856e830c47c47c2392458e6642f18af1e4b2/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L202).

**Comment by p10trk** [comment]
I can also confirm that setting `clear_env = no` in `/opt/bitnami/php/etc/php-fpm.d/custom.conf`, as suggested in #62, doesn't solve the issue.

The ability to persist certain directories and at the same time override the settings in `wp-config.php` would be very useful. In addition to the arguments mentioned by @yongzhang, it would simplify upgrades of the container and setup of a serverless infrastructure.

Instead of the administrator having to populate `wp-config.php` with custom scripts and keep it in sync with changes made in new versions of WordPress, the container could recreate `wp-config.php` on every startup, based on environment variables.

**Comment by Mauraza** [comment]
Hi @p10trk,

I see you persist the WordPress, could you check the value of the host of the database in `$PWD/wordpress-data/wp-config.php`?

**Comment by Mauraza** [comment]
Hi @p10trk,

could you try adding `wp-config.php` in `--env WORDPRESS_DATA_TO_PERSIST="wp-config.php uploads" \` ?

**Comment by p10trk** [comment]
@Mauraza If I do that, WordPress picks up `wp-config.php` as expected. However, settings are not overridden by environment variables as one could expect. E.g. `DB_HOST` is not overridden by the value of `WORDPRESS_DATABASE_HOST`.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback. To cover this use case, could you try setting the `WORDPRESS_SKIP_INSTALL` environment variable? This way it would try to recreate the `wp-config.php` configuration with the database settings.

**Comment by p10trk** [comment]
Hi @javsalgar. Do you mean like this?

```
docker container run -d --rm -p 8080:8080 \
--volume $PWD/wordpress-data:/bitnami/wordpress \
--env WORDPRESS_DATABASE_HOST=<host's IP address> \
--env WORDPRESS_DATABASE_PORT_NUMBER=3306 \
--env WORDPRESS_DATABASE_NAME=db \
--env WORDPRESS_DATABASE_USER=dbuser \
--env WORDPRESS_DATABASE_PASSWORD=dbpass \
--env WORDPRESS_SKIP_INSTALL=no \
--env WORDPRESS_DATA_TO_PERSIST=uploads \
--env WORDPRESS_EXTRA_WP_CONFIG_CONTENT="define('UPLOADS', 'uploads');" \
--env BITNAMI_DEBUG=true \
bitnami/wordpress-nginx:5.8.2
```

Unfortunately, the container still tries to connect to `localhost` instead of `host's IP address`.

**Comment by javsalgar** [comment]
Hi,

Could you try setting WORDPRESS_SKIP_INSTALL to yes? That would regenerate the wp-config.php file.

**Comment by p10trk** [comment]
Hi,

Setting WORDPRESS_SKIP_INSTALL to yes triggers regeneration of wp-config.php. Thanks for your help!

**Comment by p10trk** [comment]
Sorry, I was a bit too fast to close the issue. After further testing, I discovered that the mounted volume was unavailable (the container complained with "permission denied"). The reason was missing SELinux profile. When starting the container like this:

`
docker container run -d --rm -p 8080:8080 \
--volume $PWD/wordpress-data:/bitnami/wordpress:Z \
--env WORDPRESS_DATABASE_HOST=<host's IP address> \
--env WORDPRESS_DATABASE_PORT_NUMBER=3306 \
--env WORDPRESS_DATABASE_NAME=db \
--env WORDPRESS_DATABASE_USER=dbuser \
--env WORDPRESS_DATABASE_PASSWORD=dbpass \
--env WORDPRESS_SKIP_INSTALL=no \
--env WORDPRESS_DATA_TO_PERSIST=uploads \
--env WORDPRESS_EXTRA_WP_CONFIG_CONTENT="define('UPLOADS', 'uploads');" \
--env BITNAMI_DEBUG=true \
bitnami/wordpress-nginx:5.8.2
`

it got access to /bitnami/wordpress and was no longer regenerating wp-config.php.

**Comment by p10trk** [comment]
Unless I'm missing something, `WORDPRESS_SKIP_INSTALL` seems to be only used as a fallback value for `WORDPRESS_SKIP_BOOTSTRAP`? https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/wordpress-env.sh#L121

Any other ideas to force the container to regenerate wp-config.php at startup, and still be able to persist some files to /bitnami/wordpress?

**Comment by juan131** [comment]
Hi @p10trk 

> Unless I'm missing something, `WORDPRESS_SKIP_INSTALL` seems to be only used as a fallback value for `WORDPRESS_SKIP_BOOTSTRAP`?

Correct, they're aliases.

> Any other ideas to force the container to regenerate `wp-config.php` at startup, and still be able to persist some files to `/bitnami/wordpress`?

Currently, if you mount a volume to persist data at `/bitnami/wordpress` the condition below won't be matched on container restarts/recreations:

- https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L202

Therefore, the `wp-config.php` won't be regenerated based on the env. vars regardless what value you set in `WORDPRESS_SKIP_INSTALL` or `WORDPRESS_DATA_TO_PERSIST`.

As a workaround, I guess you can try to mount your volume at a different path (e.g. `/data`) so the init logic considers it's running a "first boot" every-time the container is restarted. Then, set `WORDPRESS_DATA_TO_PERSIST` to an empty string, and use `WORDPRESS_EXTRA_WP_CONFIG_CONTENT` to ensure that "uploads" content is stored at `/data/uploads`.

**Comment by p10trk** [comment]
@juan131 It works, thanks for your help!

The solution ended I up with is to mount a volume at `/opt/bitnami/wordpress/uploads` and start the container like this:
```
docker container run -d --rm -p 8080:8080 \
--volume $PWD/wordpress-data/uploads:/opt/bitnami/wordpress/uploads:Z \
--env WORDPRESS_DATABASE_HOST=<host's IP address> \
--env WORDPRESS_DATABASE_PORT_NUMBER=3306 \
--env WORDPRESS_DATABASE_NAME=db \
--env WORDPRESS_DATABASE_USER=dbuser \
--env WORDPRESS_DATABASE_PASSWORD=dbpass \
--env WORDPRESS_SKIP_INSTALL=yes \
--env WORDPRESS_DATA_TO_PERSIST=" " \
--env WORDPRESS_EXTRA_WP_CONFIG_CONTENT="define('UPLOADS', 'uploads');" \
--env BITNAMI_DEBUG=true \
bitnami/wordpress-nginx:5.8.2
```
