### ISSUE TITLE
provide salts via environment variables

### ISSUE THREAD

**Issue by ziodave** [bitnami/bitnami-docker-wordpress-nginx#69]
**Description**

Since I am creating multiple instances of wordpress-nginx using the same database, I'd like to be able to preset the salts by using environment variables similar to what the official [WordPress](https://hub.docker.com/_/wordpress) image does (`-e WORDPRESS_AUTH_KEY=..., -e WORDPRESS_SECURE_AUTH_KEY=..., -e WORDPRESS_LOGGED_IN_KEY=..., -e WORDPRESS_NONCE_KEY=..., -e WORDPRESS_AUTH_SALT=..., -e WORDPRESS_SECURE_AUTH_SALT=..., -e WORDPRESS_LOGGED_IN_SALT=..., -e WORDPRESS_NONCE_SALT=...`).

Would it be possible?

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
