### ISSUE TITLE
Unable to Launch WP Container Using Amazon Linux 2

### ISSUE THREAD

**Issue by richvorwaller** [bitnami/bitnami-docker-wordpress-nginx#7]
Hi all,

I'm relatively new to Docker and WordPress so apologies if I'm making any nube mistakes. I wanted to play around with this build to get familiar with WordPress on Docker, but unfortunately I'm not able to get the WordPress container up and running.

I'm installing the build on a brand new Amazon Linux 2 system. After installing Docker and Docker Compose, I'm able to pull down the container images just fine but can't get the WordPress container to run. The mariadb image runs just fine.

Here's the steps I'm taking (and can reproduce on a new Amazon Linux 2 system).

1. Spin up new Amazon Linux2 instance (t2.medium)
2. Install docker (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html)
3. Install docker compose (https://gist.github.com/npearce/6f3c7826c7499587f00957fee62f8ee9)
4. Pull down the images and use docker-compose

- `curl LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress-nginx/master/5/debian-9/docker-compose.yml`

- `docker-compose`

The docker-compose file runs up until I get an error about mounting the vhosts.conf file.
```
NFO  ==> Starting wordpress... 
INFO  ==> Starting php-fpm...
INFO  ==> Starting nginx...
2019/04/15 22:39:54 [crit] 46#0: pread() "/opt/bitnami/nginx/conf/vhosts/wordpress-vhosts.conf" failed (21: Is a directory)
nginx: [crit] pread() "/opt/bitnami/nginx/conf/vhosts/wordpress-vhosts.conf" failed (21: Is a directory)
```
I've search a couple of posts about this error, but the cause seems to be unique depending on the environment. I was wondering if there is something regarding Amazon Linux 2 or the version of docker-compose I'm using that would cause this problem or if I missing something else.

Appreciate any help you can provide.

Thanks.

- Output of `docker version`:
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Mar  4 21:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Mar  4 21:27:07 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
- Output of `docker info`:
```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.106-97.85.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.851GiB
Name: ip-172-31-38-218.us-west-2.compute.internal
ID: A5NH:SNRF:USYJ:TK5H:AHS4:H6MA:UO4O:5HDV:5HIJ:NBY2:HSGC:5XCR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
- Output of `docker-compose version` (if applicable):
```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by tompizmor** [comment]
The problem is that you are only downloading the docker-compose file but you also need the WordPress server block configuration that is being mounted locally.

Instead of downloading a single file, it is easy if you clone the whole repository and then run docker-compose up. Can you run these commands?

1. Clone repo: 
`git clone https://github.com/bitnami/bitnami-docker-wordpress-nginx`

2. Change directory:
`bitnami-docker-wordpress-nginx/5/debian-9`

3. Star containers:
`docker-compose up`

**Comment by richvorwaller** [comment]
Hi @tompizmor 

Thanks for the tip. Unfortunately, no love. Any other suggestions?

[ec2-user@ip-xxx-xx-xx-xxx ~]$ git clone https://github.com/bitnami/bitnami-docker-wordpress-nginx
Cloning into 'bitnami-docker-wordpress-nginx'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 4696 (delta 56), reused 84 (delta 34), pack-reused 4588
Receiving objects: 100% (4696/4696), 497.93 KiB | 18.44 MiB/s, done.
Resolving deltas: 100% (2743/2743), done.

[ec2-user@ip-xxx-xx-xx-xxx ~]$ ls -al
total 20
drwx------ 5 ec2-user ec2-user 188 Apr 16 19:09 .
drwxr-xr-x 3 root     root      22 Mar 29 21:26 ..
-rw------- 1 ec2-user ec2-user 801 Apr 15 22:58 .bash_history
-rw-r--r-- 1 ec2-user ec2-user  18 Jul 27  2018 .bash_logout
-rw-r--r-- 1 ec2-user ec2-user 193 Jul 27  2018 .bash_profile
-rw-r--r-- 1 ec2-user ec2-user 231 Jul 27  2018 .bashrc
drwxrwxr-x 5 ec2-user ec2-user 135 Apr 16 19:09 bitnami-docker-wordpress-nginx
-rw-rw-r-- 1 ec2-user ec2-user 787 Apr 15 22:38 docker-compose.yml
drwx------ 2 ec2-user ec2-user  29 Apr 15 22:32 .ssh
drwxr-xr-x 2 root     root       6 Apr 15 22:38 wordpress-vhosts.conf

[ec2-user@ip-xxx-xx-xx-xxx ~]$ cd bitnami-docker-wordpress-nginx/

[ec2-user@ip-xxx-xx-xx-xxx bitnami-docker-wordpress-nginx]$ docker-compose up
Creating network "bitnami-docker-wordpress-nginx_default" with the default driver
Creating volume "bitnami-docker-wordpress-nginx_mariadb_data" with local driver
Creating volume "bitnami-docker-wordpress-nginx_wordpress_data" with local driver
Creating bitnami-docker-wordpress-nginx_mariadb_1 ... done
Creating bitnami-docker-wordpress-nginx_wordpress_1 ... done
Attaching to bitnami-docker-wordpress-nginx_mariadb_1, bitnami-docker-wordpress-nginx_wordpress_1
mariadb_1    | 
mariadb_1    | Welcome to the Bitnami mariadb container
mariadb_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1    | Send us your feedback at containers@bitnami.com
mariadb_1    | 
mariadb_1    | INFO  ==> ** Starting MariaDB setup **
mariadb_1    | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
mariadb_1    | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1    | INFO  ==> Initializing mariadb database...
wordpress_1  | 
wordpress_1  | Welcome to the Bitnami wordpress-nginx container
wordpress_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx
wordpress_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues
wordpress_1  | 
wordpress_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress_1  | nami    INFO  Initializing nginx
wordpress_1  | nginx   INFO  ==> nginx.conf not found. Applying bitnami configuration...
wordpress_1  | nami    INFO  nginx successfully initialized
wordpress_1  | nami    INFO  Initializing mysql-client
wordpress_1  | nami    INFO  mysql-client successfully initialized
wordpress_1  | nami    INFO  Initializing wordpress
mariadb_1    | INFO  ==> Stopping mariadb...
mariadb_1    | INFO  ==> ** MariaDB setup finished! **
mariadb_1    | 
mariadb_1    | INFO  ==> ** Starting MariaDB **
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.38-MariaDB) starting as process 1 ...
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Warning] Could not increase number of max_open_files to more than 1024 (request: 4184)
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
mariadb_1    | 
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: Using Linux native AIO
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1    | 2019-04-16 19:10:31 140612114151296 [Note] InnoDB: Waiting for purge to start
mariadb_1    | 2019-04-16 19:10:32 140612114151296 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.42-84.2 started; log sequence number 1616727
mariadb_1    | 2019-04-16 19:10:32 140611378214656 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1    | 2019-04-16 19:10:32 140612114151296 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1    | 2019-04-16 19:10:32 140612114151296 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1    | 2019-04-16 19:10:32 140612114151296 [Warning] 'proxies_priv' entry '@% root@a9fff944fef6' ignored in --skip-name-resolve mode.
mariadb_1    | 2019-04-16 19:10:32 140612114151296 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1    | Version: '10.1.38-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
wordpress_1  | mysql-c INFO  Trying to connect to MySQL server
wordpress_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
wordpress_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
wordpress_1  | wordpre INFO 
wordpress_1  | wordpre INFO  ########################################################################
wordpress_1  | wordpre INFO   Installation parameters for wordpress:
wordpress_1  | wordpre INFO     First Name: FirstName
wordpress_1  | wordpre INFO     Last Name: LastName
wordpress_1  | wordpre INFO     Username: user
wordpress_1  | wordpre INFO     Password: **********
wordpress_1  | wordpre INFO     Email: user@example.com
wordpress_1  | wordpre INFO     Blog Name: User's Blog!
wordpress_1  | wordpre INFO     Table Prefix: wp_
wordpress_1  | wordpre INFO   (Passwords are not shown for security reasons)
wordpress_1  | wordpre INFO  ########################################################################
wordpress_1  | wordpre INFO 
wordpress_1  | nami    INFO  wordpress successfully initialized
wordpress_1  | INFO  ==> Starting wordpress... 
wordpress_1  | INFO  ==> Starting php-fpm...
wordpress_1  | INFO  ==> Starting nginx...
wordpress_1  | 2019/04/16 19:10:47 [crit] 88#0: pread() "/opt/bitnami/nginx/conf/vhosts/wordpress-vhosts.conf" failed (21: Is a directory)
wordpress_1  | nginx: [crit] pread() "/opt/bitnami/nginx/conf/vhosts/wordpress-vhosts.conf" failed (21: Is a directory)
bitnami-docker-wordpress-nginx_wordpress_1 exited with code 1

**Comment by tompizmor** [comment]
I see you have executed the docker-compose command at `bitnami-docker-wordpress-nginx/` but you should have done that at `cd bitnami-docker-wordpress-nginx/5/debian-9/`.

The error that you get is because of the file `wordpress-vhosts.conf` is being mounted in the container but you don't have in your local directory. 

Can you change your directory to `bitnami-docker-wordpress-nginx/5/debian-9/` and try again?

**Comment by richvorwaller** [comment]
@tompizmor 

Eureka! I didn't realize I was in the wrong directory. Works great. Thanks for your help.

**Comment by tompizmor** [comment]
I am glad to help! Please open a new case if you need something else
