### ISSUE TITLE
Error email send SMPT Server in Stack: Docker => Wordpress NGINX SSL

### ISSUE THREAD

**Issue by NelsonScript** [bitnami/bitnami-docker-wordpress-nginx#72]
Good morning, I'm trying to send an email through the WP Mail SMPT plugin. I must say that I have experience in handling this plugin and I have already handled it with VM in GCE with the different Bitnami stacks, however at this moment I am managing the Bitnami stack with NGINX for Wordpress with Docker and I have presented several problems .

This is the error that I present from the plugin
versions:
<img width="1276" alt="Captura de Pantalla 2022-01-25 a la(s) 5 32 37 p m" src="https://user-images.githubusercontent.com/2517635/151250187-66caaa56-19cd-4438-9f2a-b54478a0b360.png">
------------SOLUTIONS--------------

I verified that the container is pointing and the correct certificates which I created from Cloudflare
In the container logs it shows me that I must publish the correct port, according to Google Cloud Platform for security I must enable port 2525 from the firewall, in my case I have published it from the docker-compose as follows:
ports:
- '80:8080'
- '443:8443'
- '2525:587'

Finally I have tried to update the OpenSSL but in this case in the container I have not been able to do it as suggested in this post
https://community.bitnami.com/t/wp-smtp-mail-error/99669
I still haven't solved the problem and I think I've come this far, so if you can help me, I'd really appreciate it.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by blanks88** [comment]
Hey I got the same issue, but with LetsEncrypt certificate

**Comment by blanks88** [comment]
Hey @NelsonScript did you figured it out??
In my case I got Microsoft Exchange 2013 on premise, but tried with other versions and worked ok..
