### ISSUE TITLE
any plans for wordpress 5.9?

### ISSUE THREAD

**Issue by dejwsz** [bitnami/bitnami-docker-wordpress-nginx#73]
Wordpress 5.9 is there, any plans for new images for it?

**Comment by carrodher** [comment]
Our system already detected the new version, since this change is not just a patch update there is some manual work required on our side in order to adapt our test & release pipeline to the new version.
It should be released during the following days, although I can't provide a specific ETA

**Comment by carrodher** [comment]
The new version was released some days ago (https://github.com/bitnami/bitnami-docker-wordpress-nginx/commit/f577437db7aa002fb8dbde1b0f4abca4a7c18348). I'm closing this issue
