### ISSUE TITLE
php-fpm high cpu usage

### ISSUE THREAD

**Issue by antonio24073** [bitnami/bitnami-docker-wordpress-nginx#78]
### Name and Version

bitnami/wordpress-nginx:latest

### What steps will reproduce the bug?

I do nothing to this.
I got 100% cpu usage from container. The site hasn't visitors.
I tried to disable all plugins and I got a high usage yet (maybe a little less). 

```
I have no name!@container:/$ ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001           1  0.0  0.0   4400    16 ?        Ss   19:05   0:00 /bin/bash /opt/bitnami/scripts/
1001         201  0.0  0.2 310616  9920 ?        Ss   19:05   0:00 php-fpm: master process (/opt/b
1001         203  0.0  0.0  16652  1344 ?        S    19:05   0:00 nginx: master process /opt/bitn
1001         206  0.0  0.1  17604  5380 ?        S    19:05   0:02 nginx: worker process
1001         207  0.0  0.1  17636  5300 ?        S    19:05   0:02 nginx: worker process
1001        2171  0.0  0.0   4000  3136 pts/0    Ss   20:12   0:00 bash
1001        2245 79.1  5.6 468856 214548 ?       R    20:20   1:06 php-fpm: pool www
1001        2257 45.9  5.3 388880 205892 ?       R    20:20   0:13 php-fpm: pool www
1001        2260 14.0  3.5 407100 136836 ?       S    20:21   0:00 php-fpm: pool www
1001        2262 22.0  3.3 337336 129720 ?       S    20:21   0:00 php-fpm: pool www
1001        2265  0.0  0.0   7640  2712 pts/0    R+   20:21   0:00 ps aux
I have no name!@container:/$ pwdx 2245
2245: /opt/bitnami/wordpress
```

### What is the expected behavior?

low cpu usage

### What do you see instead?

high cpu usage

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by antonio24073** [comment]
I think I know. I saw the usage monitor and the date when the problem starts is a date when I publish a lot of new products and these products passed to make requests from internet bots.
Thank you
