### ISSUE TITLE
can not assign domain name to the container

### ISSUE THREAD

**Issue by jiqi963** [bitnami/bitnami-docker-wordpress-nginx#79]
### Name and Version

wordpress-nginx:5

### What steps will reproduce the bug?

download the composer file $ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress-nginx/master/docker-compose.yml
then up it.
exec to the container and config the wp-config.php file modified the WP_SITEURL and WP_HOME.
I can not find the script to restart Nginx, so I restart the container.
The domain name doesn't work, and the logs don't show anything.

Try to use Bitnami Diagnostic tool, but it's says “The path does not seem to contain a valid Bitnami installation.”

### What do you see instead?

logs do not show anythings

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-ASSET#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
