### ISSUE TITLE
App shouldn't be considered initialized if wp-config.php missing

### ISSUE THREAD

**Issue by ziodave** [bitnami/bitnami-docker-wordpress-nginx#80]
### Name and Version

bitnami/wordpress-nginx:5.9.3

### What is the problem this feature will solve?

I am using this image for development, and I would like to mount my plugin development folder to /bitnami/wordpress/wp-content/plugins/my-plugin

When I do so however, the image considers WordPress installed, because the /bitnami/wordpress folder isn't empty:

https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/prebuildfs/opt/bitnami/scripts/libpersistence.sh#L114

The image tries to restore an existing (nonexistent) app.

### What is the feature you are proposing to solve the problem?

`is_app_initialized` should check whether a wp-config.php file exists in /bitnami/wordpress.

### What alternatives have you considered?

Replacing 5/debian-10/prebuildfs/opt/bitnami/scripts/libpersistence.sh with a custom copy.

**Comment by jotamartos** [comment]
Hi @ziodave ,

Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
