### ISSUE TITLE
Adding custom env vars to config

### ISSUE THREAD

**Issue by webartistse** [bitnami/bitnami-docker-wordpress-nginx#81]
### Name and Version

bitnami/wordpress-nginx:5.9.3

### What is the problem this feature will solve?

I want better way to have control over config in Wordpress. Normally the wp-config.php is existing in the repo and have custom vars. For example it could look like this:

```
define( 'DB_NAME', $_ENV['WORDPRESS_DATABASE_NAME'] );
define( 'DB_USER', $_ENV['WORDPRESS_DATABASE_USER'] );
define( 'DB_PASSWORD', $_ENV['WORDPRESS_DATABASE_PASSWORD'] );
define( 'DB_HOST', $_ENV['WORDPRESS_DATABASE_HOST'].':'.$_ENV['WORDPRESS_DATABASE_PORT_NUMBER'] );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

define( 'WP_DEBUG', $_ENV['WP_DEBUG'] );
define( 'WP_DEBUG_LOG', $_ENV['WP_DEBUG_LOG'] );
define( 'GRAPHQL_DEBUG', $_ENV['GRAPHQL_DEBUG'] );

// Settings for Digital Ocean Spaces
define( 'DOS_KEY',                 $_ENV['DOS_KEY'] );
define( 'DOS_SECRET',              $_ENV['DOS_SECRET'] );
define( 'DOS_ENDPOINT',            $_ENV['DOS_ENDPOINT'] );
define( 'DOS_CONTAINER',           $_ENV['DOS_CONTAINER'] );
define( 'DOS_STORAGE_PATH',        $_ENV['DOS_STORAGE_PATH'] );
define( 'DOS_STORAGE_FILE_ONLY',   $_ENV['DOS_STORAGE_FILE_ONLY'] );
define( 'DOS_STORAGE_FILE_DELETE', $_ENV['DOS_STORAGE_FILE_DELETE'] );
define( 'DOS_FILTER',              $_ENV['DOS_FILTER'] );
define( 'UPLOAD_URL_PATH',         $_ENV['UPLOAD_URL_PATH'] );
define( 'UPLOAD_PATH',             $_ENV['UPLOAD_PATH'] );
```

Even if php option variables_order=EGPCS is added non of the WP vars och the custom vars is added to the $_ENV. Maybe this is for a security reasons? I dont want to add the genererated wp-config.php to the repo.

### What is the feature you are proposing to solve the problem?

I want an easy way to add custom vars on container startup to the wp-config.php file. Enable $_ENV but if its a security reason some parser that will solve this problem with some sort of whitelist. 

For example the container runs a whitelist and parse those env vars if exists like:
envvars-whitelist.txt:
```
WORDPRESS_DATABASE_NAME
WORDPRESS_DATABASE_USER
WORDPRESS_DATABASE_PASSWORD
...
DOS_KEY
DOS_SECRET
DOS_ENDPOINT
```

Example of wp-config.php:
```
define( 'DB_NAME', '${WORDPRESS_DATABASE_NAME}' );
define( 'DB_USER', '${WORDPRESS_DATABASE_USER}' );
define( 'DB_PASSWORD', '${WORDPRESS_DATABASE_PASSWORD}' );
...
define( 'DOS_KEY',                 '${DOS_KEY}' );
define( 'DOS_SECRET',              '${DOS_SECRET}' );
define( 'DOS_ENDPOINT',            '${DOS_ENDPOINT}' );
...
```

Either whitelist adds vars to $_ENV or this way as above.

### What alternatives have you considered?

Another option would be to add the substenv package to image so you can build an own parser by yourself.

**Comment by webartistse** [comment]
or maybe there is some env vars concept already existing I dont get? As I understand the container will parse config from predefined vars if the wp-config.php does not exists.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by achton** [comment]
I ran into this problem as well. I believe the reason is this bit in `/opt/bitnami/php/etc/php-fpm.d/www.conf`:

```ini
; Clear environment in FPM workers
; Prevents arbitrary environment variables from reaching FPM worker processes
; by clearing the environment in workers before env vars specified in this
; pool configuration are added.
; Setting to "no" will make all environment variables available to PHP code
; via getenv(), $_ENV and $_SERVER.
; Default Value: yes
;clear_env = no
```

So one way to achieve this would probably be a custom file in `/opt/bitnami/php/etc/php-fpm.d/` which sets `clear_env = no` and then mount that into the container.
