### ISSUE TITLE
themes and plugins upgrade issue

### ISSUE THREAD

**Issue by alianjo** [bitnami/bitnami-docker-wordpress-nginx#84]
### Name and Version

bitnami / bitnami-docker-wordpress-nginx

### What steps will reproduce the bug?

in Bitnami image WordPress Nginx when we upgrade all plugins or themes the logs are not coming while it's updating they come all together right after finishing updating.

https://user-images.githubusercontent.com/69678339/174479124-565f6dd3-a6c5-499d-8614-fe4f73838a08.mp4

### What is the expected behavior?

but in normal WordPress the logs come when we are updating all the plugins or themes (in this video I'm showing upgrading themes)

https://user-images.githubusercontent.com/69678339/174479306-55012395-4b8a-4a66-8f14-5394227fa912.mp4

### What do you see instead?

it should show logs of upgrade

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by alianjo** [comment]
@carrodher thanks I would like to contribute, please if you can reach Bitnami team, there is no such issue in https://github.com/bitnami/bitnami-docker-wordpress
