### ISSUE TITLE
Allow to customize the URL for non multisite installs

### ISSUE THREAD

**Issue by ziodave** [bitnami/bitnami-docker-wordpress-nginx#85]
### Name and Version

bitnami/wordpress-nginx:6

### What is the problem this feature will solve?

ATM it is possible to configure the URL for multisite installs but not for standard installs. For standard installs the installer forces the URL to `localhost`.

https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/ad732d2ca0cbf58f4614cf8108e1d9b0eae1b5da/6/debian-11/rootfs/opt/bitnami/scripts/libwordpress.sh#L288-L303

It would be nice to be able to customize the URL for standard installs as well.

### What is the feature you are proposing to solve the problem?

I propose to provide to check whether the url is providing the `--url` switch in `WORDPRESS_EXTRA_INSTALL_ARGS` in which case the script should refrain from setting `localhost`.

### What alternatives have you considered?

Overriding the local `libwordpress.sh` file.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-wordpress-nginx#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ziodave** [comment]
Closing in favor of a more complete description of the use case, https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/86
